### ISSUE TITLE
No such file or directory :'bazel'

### ISSUE THREAD

**Issue by Samshekar** [homuler/MediaPipeUnityPlugin#103]
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel build -c opt //mediapipe_api:mediapipe_proto_srcs`
Traceback (most recent call last):
  File "/home/som/MediaPipeUnityPlugin/build.py", line 341, in <module>
    Argument().command().run()
  File "/home/som/MediaPipeUnityPlugin/build.py", line 96, in run
    self._run_command(self._build_proto_srcs_commands())
  File "/home/som/MediaPipeUnityPlugin/build.py", line 43, in _run_command
    return subprocess.run(command_list, check=True)
  File "/usr/lib/python3.9/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'bazel'

**Comment by emreboyraz0** [comment]
follow [this](https://google.github.io/mediapipe/getting_started/install.html#installing-on-macos)
You need to download Homebrew and bazel.
