### ISSUE TITLE
Can't build native libraries :-  Protobuf compile issue

### ISSUE THREAD

**Issue by MandarComXr** [homuler/MediaPipeUnityPlugin#1036]
### Plugin Version or Commit ID

01cdd56

### Unity Version

2019.4.21f1

### Your Host OS

Windows 10 Home

### Target Platform

UnityEditor

### [Windows Only] Visual Studio C++ and Windows SDK Version

Visual Studio C++  14.29.30133
Win SDK  10.0.19041.685

### Command Sequences

Have manually set these Environment Variables using GUI

BAZEL_VS=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC
BAZEL_VC_FULL_VERSION=14.29.30133
BAZEL_WINSDK_FULL_VERSION=10.0.19041.685

### Log

```make
$ python build.py build --android arm64 --solutions hands pose --linkopt=-s -vv
WARNING: Running Bazel server needs to be killed, because the startup options are different.
Starting local Bazel server and connecting to it...
Loading:
Loading:
DEBUG: C:/_bzl/66gvj5bb/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/66gvj5bb/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/_bzl/66gvj5bb/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'flatbuffers' because it already exists.
DEBUG: C:/_bzl/66gvj5bb/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_googlesource_code_re2' because it already exists.
DEBUG: C:/_bzl/66gvj5bb/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/66gvj5bb/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/66gvj5bb/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/66gvj5bb/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'zlib' because it already exists.
DEBUG: C:/_bzl/66gvj5bb/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/66gvj5bb/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/66gvj5bb/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/66gvj5bb/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/66gvj5bb/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/_bzl/66gvj5bb/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_github_glog_glog' because it already exists.
Loading:
Loading: 1 packages loaded
Analyzing: target //mediapipe_api:mediapipe_proto_srcs (1 packages loaded, 0 targets configured)
Analyzing: target //mediapipe_api:mediapipe_proto_srcs (41 packages loaded, 19 targets configured)
Analyzing: target //mediapipe_api:mediapipe_proto_srcs (102 packages loaded, 244 targets configured)
Analyzing: target //mediapipe_api:mediapipe_proto_srcs (103 packages loaded, 244 targets configured)
INFO: Analyzed target //mediapipe_api:mediapipe_proto_srcs (115 packages loaded, 1089 targets configured).
INFO: Found 1 target...
[0 / 56] [Prepa] BazelWorkspaceStatusAction stable-status.txt
[13 / 343] Compiling src/google/protobuf/compiler/csharp/csharp_generator.cc [for tool]; 1s local ... (128 actions, 8 running)
[14 / 343] Compiling src/google/protobuf/compiler/csharp/csharp_generator.cc [for tool]; 2s local ... (128 actions, 8 running)
[14 / 343] Compiling src/google/protobuf/compiler/csharp/csharp_generator.cc [for tool]; 3s local ... (128 actions, 9 running)
[18 / 343] Compiling src/google/protobuf/util/internal/protostream_objectsource.cc [for tool]; 4s local ... (128 actions, 8 running)
[21 / 343] [Sched] Compiling src/google/protobuf/any_lite.cc [for tool]; 5s ... (128 actions, 8 running)
[22 / 343] [Sched] Compiling src/google/protobuf/any_lite.cc [for tool]; 6s ... (128 actions, 8 running)
[26 / 343] [Sched] Compiling src/google/protobuf/any_lite.cc [for tool]; 7s ... (128 actions, 8 running)
[27 / 343] [Sched] Compiling src/google/protobuf/any_lite.cc [for tool]; 8s ... (128 actions, 8 running)
[32 / 343] [Sched] Compiling src/google/protobuf/compiler/java/java_map_field_lite.cc [for tool]; 9s ... (128 actions, 8 running)
[32 / 343] [Sched] Compiling src/google/protobuf/compiler/java/java_map_field_lite.cc [for tool]; 10s ... (128 actions, 8 running)
[32 / 343] [Sched] Compiling src/google/protobuf/compiler/zip_writer.cc [for tool]; 12s ... (128 actions, 9 running)
[34 / 343] [Sched] Compiling src/google/protobuf/compiler/csharp/csharp_helpers.cc [for tool]; 13s ... (128 actions, 8 running)
[35 / 343] [Sched] Compiling src/google/protobuf/compiler/java/java_name_resolver.cc [for tool]; 14s ... (128 actions, 8 running)
[35 / 343] [Sched] Compiling src/google/protobuf/generated_message_table_driven.cc [for tool]; 15s ... (128 actions, 9 running)
[39 / 343] [Sched] Compiling src/google/protobuf/compiler/objectivec/objectivec_message.cc [for tool]; 16s ... (128 actions, 9 running)
ERROR: C:/_bzl/66gvj5bb/external/com_google_protobuf/BUILD:420:11: Compiling src/google/protobuf/compiler/subprocess.cc [for tool] failed: (Exit 2): cl.exe failed: error executing command (from target @com_google_protobuf//:protoc_lib)
  cd /d C:/_bzl/66gvj5bb/execroot/mediapipe_api
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.685\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.685\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.685\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.685\cppwinrt
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\\Extensions\Microsoft\IntelliCode\CLI;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\devinit;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\\MSBuild\Current\Bin;C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\;;C:\WINDOWS\system32;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\Linux\bin\ConnectionManagerExe
    SET PWD=/proc/self/cwd
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\teamc\AppData\Local\Temp
    SET TMP=C:\Users\teamc\AppData\Local\Temp
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe @bazel-out/x64_windows-opt-exec-50AE0418/bin/external/com_google_protobuf/_objs/protoc_lib/subprocess.obj.params
# Configuration: 8ccf8358287208af39f1eb5486694edd73aa901524b0e1b719be5f17c259aa82
# Execution platform: @local_execution_config_platform//:platform
external/com_google_protobuf/src\google/protobuf/compiler/subprocess.h(40): fatal error C1083: Cannot open include file: 'windows.h': No such file or directory
Target //mediapipe_api:mediapipe_proto_srcs failed to build
INFO: Elapsed time: 27.899s, Critical Path: 16.99s
INFO: 157 processes: 129 internal, 28 local.
FAILED: Build did NOT complete successfully
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --linkopt=-s --action_env PYTHON_BIN_PATH="C://Users//teamc//AppData//Local//Programs//Python//Python311//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures --//mediapipe_api:solutions=hands,pose //mediapipe_api:mediapipe_proto_srcs`
Traceback (most recent call last):
  File "D:\Projects\Reactive_Android\MediaPipeUnityPlugin\build.py", line 470, in <module>
    Argument().command().run()
  File "D:\Projects\Reactive_Android\MediaPipeUnityPlugin\build.py", line 114, in run
    self._run_command(self._build_proto_srcs_commands())
  File "D:\Projects\Reactive_Android\MediaPipeUnityPlugin\build.py", line 56, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teamc\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --linkopt=-s --action_env PYTHON_BIN_PATH="C://Users//teamc//AppData//Local//Programs//Python//Python311//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures --//mediapipe_api:solutions=hands,pose //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 1.
```

**Comment by homuler** [comment]
> fatal error C1083: Cannot open include file: 'windows.h': No such file or directory

Maybe you've not installed Install Visual C++ Build Tools 2019 or WinSDK properly.
Note that you don't need to build the library (you can download it from the release page), and even if you want build it with your favorite settings, you can use the GitHub Action workflow.

**Comment by megawattfs** [comment]
@homuler I am running into a similar issue, needing to adapt the mediapipe library but unable to build it on Windows. Can you share how you modified the mediapipe build settings to produce a dll output? And which GitHub Action workflow are you referring to? Thank you

**Comment by megawattfs** [comment]
> @homuler I am running into a similar issue, needing to adapt the mediapipe library but unable to build it on Windows. Can you share how you modified the mediapipe build settings to produce a dll output? And which GitHub Action workflow are you referring to? Thank you

Never mind, I see you were referring to a workflow for this repo, not the mediapipe repo. I'll take a look.
