### ISSUE TITLE
WinError 2 cannot find file

### ISSUE THREAD

**Issue by ratyes** [homuler/MediaPipeUnityPlugin#104]
While doing the installation I get the next error:

DEBUG (build.py): Running `nuget install -o .nuget`
Traceback (most recent call last):
  File "C:\Bitbucket\mediapipe_repo\MediaPipeUnityPlugin\build.py", line 341, in <module>
    Argument().command().run()
  File "C:\Bitbucket\mediapipe_repo\MediaPipeUnityPlugin\build.py", line 103, in run
    self._run_command(self._build_proto_dlls_commands())
  File "C:\Bitbucket\mediapipe_repo\MediaPipeUnityPlugin\build.py", line 43, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

Does some know how to fix this?

Command is: python build.py build --desktop gpu -v

**Comment by homuler** [comment]
First, you cannot build with GPU enabled on Windows, so please run `python build.py build --desktop cpu -v`.

And if you have not installed `nuget` yet, please install it (cf. https://github.com/homuler/MediaPipeUnityPlugin#nuget-cli).

**Comment by ratyes** [comment]
Forgot to add the NuGet PATH variable. Also, I needed to restart my command prompt.
Thank you for the advice Homuler.
