### ISSUE TITLE
Build issue for windows

### ISSUE THREAD

**Issue by monit-org** [homuler/MediaPipeUnityPlugin#1051]
### Plugin Version or Commit ID

0.10.1

### Unity Version

2022.3.6f1

### Your Host OS

Windows

### Target Platform

Windows Standalone

### [Windows Only] Visual Studio C++ and Windows SDK Version

Visual Studio C++: 14.29.30133
Windows SDK: 10.0.19041.0

### Command Sequences

set BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC
set BAZEL_VS=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
set BAZEL_VC_FULL_VERSION=14.29.30133
set BAZEL_WINSDK_FULL_VERSION=10.0.19041.0
*create python3.9 (3.9.13) virtual environment, and active it* 
pip install numpy
set PYTHON_BIN_PATH=C:\Users\lenovo\Downloads\MediaPipeUnityPlugin-master\env\Scripts\python.exe
python build.py build --desktop cpu  -v 

### Log

INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//lenovo//Downloads//MediaPipeUnityPlugin-master//env//Scripts//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION //mediapipe_api:mediapipe_proto_srcs`
INFO: Repository local_execution_config_python instantiated at:
  C:/users/lenovo/downloads/mediapipeunityplugin-master/WORKSPACE:480:14: in <toplevel>
  C:/_bzl/ztbygm3j/external/org_tensorflow/tensorflow/workspace2.bzl:985:19: in workspace
  C:/_bzl/ztbygm3j/external/org_tensorflow/tensorflow/workspace2.bzl:100:27: in _tf_toolchains
  C:/_bzl/ztbygm3j/external/org_tensorflow/tensorflow/tools/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  C:/_bzl/ztbygm3j/external/org_tensorflow/tensorflow/tools/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  C:/_bzl/ztbygm3j/external/org_tensorflow/third_party/py/python_configure.bzl:279:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/_bzl/ztbygm3j/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/_bzl/ztbygm3j/external/org_tensorflow/third_party/py/python_configure.bzl", line 143, column 52, in _check_python_bin
                result = raw_exec(repository_ctx, [get_bash_bin(repository_ctx), "-c", cmd])
        File "C:/_bzl/ztbygm3j/external/org_tensorflow/third_party/remote_config/common.bzl", line 88, column 26, in get_bash_bin
                bash_bin_path = which(repository_ctx, "bash")
        File "C:/_bzl/ztbygm3j/external/org_tensorflow/third_party/remote_config/common.bzl", line 27, column 22, in which
                out = execute(
        File "C:/_bzl/ztbygm3j/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
INFO: Could not find files for the given pattern(s).
ERROR: C:/users/lenovo/downloads/mediapipeunityplugin-master/WORKSPACE:480:14: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):
        File "C:/_bzl/ztbygm3j/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/_bzl/ztbygm3j/external/org_tensorflow/third_party/py/python_configure.bzl", line 143, column 52, in _check_python_bin
                result = raw_exec(repository_ctx, [get_bash_bin(repository_ctx), "-c", cmd])
        File "C:/_bzl/ztbygm3j/external/org_tensorflow/third_party/remote_config/common.bzl", line 88, column 26, in get_bash_bin
                bash_bin_path = which(repository_ctx, "bash")
        File "C:/_bzl/ztbygm3j/external/org_tensorflow/third_party/remote_config/common.bzl", line 27, column 22, in which
                out = execute(
        File "C:/_bzl/ztbygm3j/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
INFO: Could not find files for the given pattern(s).
INFO: Repository nodejs_windows_amd64 instantiated at:
  C:/users/lenovo/downloads/mediapipeunityplugin-master/WORKSPACE:514:18: in <toplevel>
  C:/_bzl/ztbygm3j/external/build_bazel_rules_nodejs/internal/node/node_repositories.bzl:50:31: in node_repositories
  C:/_bzl/ztbygm3j/external/rules_nodejs/nodejs/repositories.bzl:400:26: in nodejs_register_toolchains
Repository rule node_repositories defined at:
  C:/_bzl/ztbygm3j/external/rules_nodejs/nodejs/repositories.bzl:374:36: in <toplevel>
INFO: Repository com_google_protobuf instantiated at:
  C:/users/lenovo/downloads/mediapipeunityplugin-master/WORKSPACE:85:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/ztbygm3j/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: Repository command failed
INFO: Could not find files for the given pattern(s).
INFO: Elapsed time: 5.114s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (34 packages loaded, 0 targets configured)
    currently loading: @com_google_mediapipe//mediapipe/util/tracking ... (28 packages)
    Fetching repository @npm; Restarting.
    Fetching repository @yarn; Restarting.
    Fetching https://nodejs.org/dist/v16.19.0/node-v16.19.0-win-x64.zip
Traceback (most recent call last):
  File "C:\Users\lenovo\Downloads\MediaPipeUnityPlugin-master\build.py", line 470, in <module>
    Argument().command().run()
  File "C:\Users\lenovo\Downloads\MediaPipeUnityPlugin-master\build.py", line 114, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\Users\lenovo\Downloads\MediaPipeUnityPlugin-master\build.py", line 56, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//lenovo//Downloads//MediaPipeUnityPlugin-master//env//Scripts//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 1.

**Comment by homuler** [comment]
It builds successfully on [GitHub Actions](https://github.com/homuler/MediaPipeUnityPlugin/actions/workflows/build-package.yml), so please use that.

See also https://github.com/homuler/MediaPipeUnityPlugin#hammer_and_wrench-installation.
