### ISSUE TITLE
PYTHON_BIN_PATH is not executable - installation problem

### ISSUE THREAD

**Issue by CR4YZ3R** [homuler/MediaPipeUnityPlugin#1266]
### Plugin Version or Commit ID

v0.15.0

### Unity Version

6000.0.23f1

### Your Host OS

Windows 11 Home

### Target Platform

UnityEditor

### Command Sequences

python build.py build --desktop cpu

### Log

INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//xxxx//AppData//Local//Programs//Python//Python313//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures //mediapipe_api:mediapipe_proto_srcs`
INFO: Repository local_execution_config_python instantiated at:
  C:/users/xxxx/downloads/mediapipeunityplugin-master/mediapipeunityplugin-master/WORKSPACE:515:14: in <toplevel>
  C:/_bzl/55vfe4qp/external/org_tensorflow/tensorflow/workspace2.bzl:928:19: in workspace
  C:/_bzl/55vfe4qp/external/org_tensorflow/tensorflow/workspace2.bzl:101:27: in _tf_toolchains
  C:/_bzl/55vfe4qp/external/org_tensorflow/tensorflow/tools/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  C:/_bzl/55vfe4qp/external/org_tensorflow/tensorflow/tools/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  C:/_bzl/55vfe4qp/external/org_tensorflow/third_party/py/non_hermetic/python_configure.bzl:276:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/_bzl/55vfe4qp/external/org_tensorflow/third_party/py/non_hermetic/python_configure.bzl", line 209, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/_bzl/55vfe4qp/external/org_tensorflow/third_party/py/non_hermetic/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/_bzl/55vfe4qp/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C://Users//xxxx//AppData//Local//Programs//Python//Python313//python.exe' is not executable. Is it the python binary?
ERROR: C:/users/xxxx/downloads/mediapipeunityplugin-master/mediapipeunityplugin-master/WORKSPACE:515:14: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):
        File "C:/_bzl/55vfe4qp/external/org_tensorflow/third_party/py/non_hermetic/python_configure.bzl", line 209, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/_bzl/55vfe4qp/external/org_tensorflow/third_party/py/non_hermetic/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/_bzl/55vfe4qp/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C://Users//xxxx//AppData//Local//Programs//Python//Python313//python.exe' is not executable. Is it the python binary?
INFO: Repository nodejs_windows_amd64 instantiated at:
  C:/users/xxxx/downloads/mediapipeunityplugin-master/mediapipeunityplugin-master/WORKSPACE:544:18: in <toplevel>
  C:/_bzl/55vfe4qp/external/build_bazel_rules_nodejs/internal/node/node_repositories.bzl:50:31: in node_repositories
  C:/_bzl/55vfe4qp/external/rules_nodejs/nodejs/repositories.bzl:400:26: in nodejs_register_toolchains
Repository rule node_repositories defined at:
  C:/_bzl/55vfe4qp/external/rules_nodejs/nodejs/repositories.bzl:374:36: in <toplevel>
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: Configuration Error: --define PYTHON_BIN_PATH='C://Users//xxxx//AppData//Local//Programs//Python//Python313//python.exe' is not executable. Is it the python binary?
INFO: Elapsed time: 1.668s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: @mediapipe//mediapipe/framework ... (32 packages)
    Fetching repository @npm; Restarting.
    Fetching repository @yarn; Restarting.
    Fetching https://nodejs.org/dist/v16.19.0/node-v16.19.0-win-x64.zip; 17.1 MiB (17,922,619B)
    Fetching repository @com_google_protobuf; starting
    Fetching C:/_bzl/55vfe4qp/external/com_google_protobuf; Extracting v3.19.1.tar.gz
Traceback (most recent call last):
  File "C:\Users\xxxx\Downloads\MediaPipeUnityPlugin-master\MediaPipeUnityPlugin-master\build.py", line 475, in <module>
    Argument().command().run()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\xxxx\Downloads\MediaPipeUnityPlugin-master\MediaPipeUnityPlugin-master\build.py", line 114, in run
    self._run_command(self._build_proto_srcs_commands())
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\Downloads\MediaPipeUnityPlugin-master\MediaPipeUnityPlugin-master\build.py", line 56, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 577, in run
    raise CalledProcessError(retcode, process.args,
                             output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//xxxx//AppData//Local//Programs//Python//Python313//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 1.

### Additional Context

_No response_

**Comment by lj-cug** [comment]
I encountered the same problem!

**Comment by homuler** [comment]
There were similar issues in the past, so please try searching for them.
Alternatively, it could be that it doesn't work with the newer version of Python.

In any case, I no longer support building in individual local environments, so if you need to build it, please fork the repository and use the GitHub Actions [workflow](https://github.com/homuler/MediaPipeUnityPlugin/actions/workflows/build-package.yml) (ref. https://github.com/homuler/MediaPipeUnityPlugin?tab=readme-ov-file#hammer_and_wrench-installation).
Note that you can download the pre-built package from the release page.

**Comment by CR4YZ3R** [comment]
Ok, thanks for the answer! :)
