### ISSUE TITLE
fatal error: 'EGL/egl.h' file not found

### ISSUE THREAD

**Issue by jignesh-comxr** [homuler/MediaPipeUnityPlugin#138]
**System information**
- OS Platform and Distribution : `macOS Catalina (v 10.15.7)`
- Target : `Desktop GPU`
- Bazel version: `3.7.2`
- Python version: `3.9.2`
- GCC/G++ version: `12.0.0`
- Unity version: ~
- Android NDK version (if building for Android): ~
- Xcode version (if building for iOS): ~

**Describe the problem**
Facing error `'EGL/egl.h' file not found` on running the build command for Desktop GPU.

**Steps to reproduce the issue**
- Clone the repository
- Install all the prerequisites 
- Run command `python build.py build --desktop gpu -v`

**Full logs**

```
Admins-iMac:MediaPipeUnityPlugin Administrator$ python build.py build --desktop gpu -v
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel build -c opt //mediapipe_api:mediapipe_proto_srcs`
Starting local Bazel server and connecting to it...
INFO: Analyzed target //mediapipe_api:mediapipe_proto_srcs (42 packages loaded, 807 targets configured).
INFO: Found 1 target...
Target //mediapipe_api:mediapipe_proto_srcs up-to-date:
  bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip
INFO: Elapsed time: 50.593s, Critical Path: 2.14s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
DEBUG (build.py): Unarchiving 'bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip' to 'build/Scripts/Protobuf'...
INFO (build.py): Built protobuf sources
INFO (build.py): Downloading protobuf dlls...
DEBUG (build.py): Running `nuget install -o .nuget`
Feeds used:
  /Users/Administrator/.nuget/packages/
  https://api.nuget.org/v3/index.json

Restoring NuGet package Google.Protobuf.3.15.6.
Adding package 'Google.Protobuf.3.15.6' to folder '/Users/Administrator/Documents/MediaPipeSizeReduction/MediaPipeUnityPlugin/.nuget'
Added package 'Google.Protobuf.3.15.6' to folder '/Users/Administrator/Documents/MediaPipeSizeReduction/MediaPipeUnityPlugin/.nuget'
Restoring NuGet package System.Buffers.4.4.0.
Adding package 'System.Buffers.4.4.0' to folder '/Users/Administrator/Documents/MediaPipeSizeReduction/MediaPipeUnityPlugin/.nuget'
Added package 'System.Buffers.4.4.0' to folder '/Users/Administrator/Documents/MediaPipeSizeReduction/MediaPipeUnityPlugin/.nuget'
Restoring NuGet package System.Memory.4.5.3.
Adding package 'System.Memory.4.5.3' to folder '/Users/Administrator/Documents/MediaPipeSizeReduction/MediaPipeUnityPlugin/.nuget'
Added package 'System.Memory.4.5.3' to folder '/Users/Administrator/Documents/MediaPipeSizeReduction/MediaPipeUnityPlugin/.nuget'
Restoring NuGet package System.Runtime.CompilerServices.Unsafe.4.5.2.
Adding package 'System.Runtime.CompilerServices.Unsafe.4.5.2' to folder '/Users/Administrator/Documents/MediaPipeSizeReduction/MediaPipeUnityPlugin/.nuget'
Added package 'System.Runtime.CompilerServices.Unsafe.4.5.2' to folder '/Users/Administrator/Documents/MediaPipeSizeReduction/MediaPipeUnityPlugin/.nuget'
DEBUG (build.py): Copying '.nuget/System.Buffers.4.4.0/lib/netstandard2.0/System.Buffers.dll' to 'build/Plugins/Protobuf/System.Buffers.dll'...
DEBUG (build.py): Creating 'build/Plugins/Protobuf'...
DEBUG (build.py): Changing the mode of 'build/Plugins/Protobuf/System.Buffers.dll'...
DEBUG (build.py): Copying '.nuget/Google.Protobuf.3.15.6/lib/netstandard2.0/Google.Protobuf.dll' to 'build/Plugins/Protobuf/Google.Protobuf.dll'...
DEBUG (build.py): Changing the mode of 'build/Plugins/Protobuf/Google.Protobuf.dll'...
DEBUG (build.py): Copying '.nuget/System.Runtime.CompilerServices.Unsafe.4.5.2/lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll' to 'build/Plugins/Protobuf/System.Runtime.CompilerServices.Unsafe.dll'...
DEBUG (build.py): Changing the mode of 'build/Plugins/Protobuf/System.Runtime.CompilerServices.Unsafe.dll'...
DEBUG (build.py): Copying '.nuget/System.Memory.4.5.3/lib/netstandard2.0/System.Memory.dll' to 'build/Plugins/Protobuf/System.Memory.dll'...
DEBUG (build.py): Changing the mode of 'build/Plugins/Protobuf/System.Memory.dll'...
INFO (build.py): Downloaded protobuf dlls
INFO (build.py): Building resource files
DEBUG (build.py): Running `bazel build -c opt //mediapipe_api:mediapipe_assets`
INFO: Analyzed target //mediapipe_api:mediapipe_assets (18 packages loaded, 46 targets configured).
INFO: Found 1 target...
Target //mediapipe_api:mediapipe_assets up-to-date:
  bazel-bin/mediapipe_api/mediapipe_assets.zip
INFO: Elapsed time: 8.669s, Critical Path: 7.58s
INFO: 38 processes: 1 internal, 37 darwin-sandbox.
INFO: Build completed successfully, 38 total actions
DEBUG (build.py): Unarchiving 'bazel-bin/mediapipe_api/mediapipe_assets.zip' to 'build/Resources'...
INFO (build.py): Built resource files
INFO (build.py): Building native libraries for Desktop...
DEBUG (build.py): Running `bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 //mediapipe_api:mediapipe_desktop`
INFO: Build option --copt has changed, discarding analysis cache.
INFO: Analyzed target //mediapipe_api:mediapipe_desktop (129 packages loaded, 9128 targets configured).
INFO: Found 1 target...
INFO: From ProtoCompile external/com_google_mediapipe/mediapipe/calculators/image/set_alpha_calculator.pb.h:
bazel-out/darwin-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_mediapipe/mediapipe/calculators/image/recolor_calculator.pb.h:
bazel-out/darwin-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_mediapipe/mediapipe/calculators/tflite/tflite_tensors_to_segmentation_calculator.pb.h:
bazel-out/darwin-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_mediapipe/mediapipe/graphs/object_detection_3d/calculators/model_matrix.pb.h:
bazel-out/darwin-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_mediapipe/mediapipe/framework/tool/switch_container.pb.h:
bazel-out/darwin-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
ERROR: /private/var/tmp/_bazel_Administrator/a8e4317fcddf583bd86af9908b886390/external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/converters/BUILD:23:11: C++ compilation of rule '@org_tensorflow//tensorflow/lite/delegates/gpu/gl/converters:bhwc_to_phwc4' failed (Exit 1): wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 41 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 41 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/converters/bhwc_to_phwc4.cc:16:
In file included from external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/converters/bhwc_to_phwc4.h:22:
In file included from external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/command_queue.h:24:
In file included from external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/gl_program.h:24:
In file included from external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/gl_shader.h:23:
external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/portable_gl31.h:21:10: fatal error: 'EGL/egl.h' file not found
#include <EGL/egl.h>
         ^~~~~~~~~~~
1 error generated.
Target //mediapipe_api:mediapipe_desktop failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 28.600s, Critical Path: 19.21s
INFO: 170 processes: 133 internal, 37 darwin-sandbox.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "/Users/Administrator/Documents/MediaPipeSizeReduction/MediaPipeUnityPlugin/build.py", line 362, in <module>
    Argument().command().run()
  File "/Users/Administrator/Documents/MediaPipeSizeReduction/MediaPipeUnityPlugin/build.py", line 128, in run
    self._run_command(self._build_desktop_commands())
  File "/Users/Administrator/Documents/MediaPipeSizeReduction/MediaPipeUnityPlugin/build.py", line 47, in _run_command
    return subprocess.run(command_list, check=True)
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', 'build', '-c', 'opt', '--copt', '-DMESA_EGL_NO_X11_HEADERS', '--copt', '-DEGL_NO_X11', '//mediapipe_api:mediapipe_desktop']' returned non-zero exit status 1.
Admins-iMac:MediaPipeUnityPlugin Administrator$ 

```

**Comment by homuler** [comment]
You cannot build native libraries with GPU enabled on macOS.
https://github.com/homuler/MediaPipeUnityPlugin#platforms

Please run `python build.py build --desktop cpu -v` instead.

**Comment by jignesh-comxr** [comment]
@homuler 

Ran the command for CPU and it worked perfectly. Thanks. 
Closing this issue.
