### ISSUE TITLE
[MacOS] Error on build for 0.5.1 Release

### ISSUE THREAD

**Issue by tinatinaZ** [homuler/MediaPipeUnityPlugin#143]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): MacOS 10.15
- Target (e.g. desktop cpu, android arm64): desktop cpu
- Bazel version: 3.7.2
- Python version: 3.9.4
- GCC/G++ version: 12.0.0
- Unity version: 2021.3.0f1
- Android NDK version (if building for Android): None
- Xcode version (if building for iOS): None

**Describe the problem**
I followed the README to build 0.5.1 version, after I ran `python build.py build --desktop cpu -v` it returned following error.

**Full logs**
```
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel build -c opt //mediapipe_api:mediapipe_proto_srcs`
Starting local Bazel server and connecting to it...
INFO: SHA256 (https://github.com/bazelbuild/rules_foreign_cc/archive/main.zip) = e4dec87f68314e448b771434a3c7d49e3d2a6e6fc32b556fc23a38d892e85409
DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "e4dec87f68314e448b771434a3c7d49e3d2a6e6fc32b556fc23a38d892e85409"
DEBUG: Repository rules_foreign_cc instantiated at:
  /Users/christina/Downloads/MediaPipeUnityPlugin-0.5.1/WORKSPACE:79:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_christina/ce481739353571d3bffde06367bf7e9c/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: error loading package '': cannot load '@rules_foreign_cc//:workspace_definitions.bzl': no such file
INFO: Elapsed time: 9.811s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
Traceback (most recent call last):
  File "/Users/christina/Downloads/MediaPipeUnityPlugin-0.5.1/build.py", line 341, in <module>
    Argument().command().run()
  File "/Users/christina/Downloads/MediaPipeUnityPlugin-0.5.1/build.py", line 96, in run
    self._run_command(self._build_proto_srcs_commands())
  File "/Users/christina/Downloads/MediaPipeUnityPlugin-0.5.1/build.py", line 43, in _run_command
    return subprocess.run(command_list, check=True)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', 'build', '-c', 'opt', '//mediapipe_api:mediapipe_proto_srcs']' returned non-zero exit status 1.
```
**Additional context**

**Comment by tinatinaZ** [comment]
emmm...There is no **workspace_definitions.bzl** on the main branch of [rules_foreign_cc](https://github.com/bazelbuild/rules_foreign_cc/). 

So I replaced
```
http_archive(
   name = "rules_foreign_cc",
   strip_prefix = "rules_foreign_cc-main",
   url = "https://github.com/bazelbuild/rules_foreign_cc/archive/main.zip",
)
```
in the **WORKSPACE** file by
```
http_archive(
   name = "rules_foreign_cc",
   strip_prefix = "rules_foreign_cc-master",
   url = "https://github.com/bazelbuild/rules_foreign_cc/archive/master.zip",
)
```
and problem solved. :tada::tada::tada:
