### ISSUE TITLE
failed: (Exit 2): cl.exe failed: error executing command

### ISSUE THREAD

**Issue by Arham-Aalam** [homuler/MediaPipeUnityPlugin#226]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): Windows
- Target (e.g. desktop cpu, android arm64): desktop cpu
- Bazel version: 4.1.0
- Python version: 3.7.8
- GCC/G++ version: 19.16.27045 for x64
- Unity version: 2020
- Android NDK version (if building for Android): 
- Xcode version (if building for iOS):

**Describe the problem**
Getting this error while building:
cl.exe failed: error executing command C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE ... (remaining 37 argument(s) skipped)

**Steps to reproduce the issue**
I have setup the Bazel and other VS settings properly, I have also verified the installation by building Medipipe's official hello world program.
Python path is also set with Numpy.
I have installed the nuget.

Logs:

```
INFO: From ProtoCompile external/com_google_mediapipe/mediapipe/calculators/tensor/inference_calculator.pb.h [for host]:
bazel-out/host/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_mediapipe/mediapipe/calculators/util/detections_to_rects_calculator.pb.h:
bazel-out/x64_windows-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_mediapipe/mediapipe/calculators/tflite/ssd_anchors_calculator.pb.h [for host]:
bazel-out/host/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From Compiling absl/flags/internal/private_handle_accessor.cc:
cl : Command line warning D9025 : overriding '/w' with '/W3'
INFO: From Compiling absl/flags/internal/program_name.cc:
cl : Command line warning D9025 : overriding '/w' with '/W3'
INFO: From Compiling tensorflow/lite/kernels/internal/transpose_utils.cc:
cl : Command line warning D9002 : ignoring unknown option '-O3'
INFO: From Compiling tensorflow/lite/util.cc:
cl : Command line warning D9002 : ignoring unknown option '-O3'
INFO: From Compiling tensorflow/lite/kernels/cpu_backend_context.cc:
cl : Command line warning D9002 : ignoring unknown option '-O3'
ERROR: C:/_bzl/76rdmxqm/external/com_google_mediapipe/mediapipe/util/tracking/BUILD:398:11: Compiling mediapipe/util/tracking/streaming_buffer.cc failed: (Exit 2): cl.exe failed: error executing command C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE ... (remaining 37 argument(s) skipped)
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(352): error C2244: 'mediapipe::StreamingBuffer::AddData': unable to match function definition to an existing declaration
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(351): note: see declaration of 'mediapipe::StreamingBuffer::AddData'
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(352): note: definition
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(352): note: 'void mediapipe::StreamingBuffer::AddData(const std::vector<std::string,std::allocator<_Ty>> &,std::unique_ptr<Types,std::default_delete<Types>>...)'
        with
        [
            _Ty=std::string
        ]
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(352): note: existing declarations
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(352): note: 'void mediapipe::StreamingBuffer::AddData(const std::vector<std::string,std::allocator<_Ty>> &,std::unique_ptr<Types,std::default_delete<Types>>...)'
        with
        [
            _Ty=std::string
        ]
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(369): error C2244: 'mediapipe::StreamingBuffer::AddDataImpl': unable to match function definition to an existing declaration
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(367): note: see declaration of 'mediapipe::StreamingBuffer::AddDataImpl'
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(369): note: definition
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(369): note: 'void mediapipe::StreamingBuffer::AddDataImpl(const std::vector<std::string,std::allocator<_Ty>> &,std::unique_ptr<_Ty,std::default_delete<_Ty>>,std::unique_ptr<Pointers,std::default_delete<Pointers>>...)'
        with
        [
            _Ty=std::string
        ]
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(369): note: existing declarations
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(369): note: 'void mediapipe::StreamingBuffer::AddDataImpl(const std::vector<std::string,std::allocator<_Ty>> &)'
        with
        [
            _Ty=std::string
        ]
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(369): note: 'void mediapipe::StreamingBuffer::AddDataImpl(const std::vector<std::string,std::allocator<_Ty>> &,std::unique_ptr<_Ty,std::default_delete<_Ty>>,std::unique_ptr<Pointers,std::default_delete<Pointers>>...)'
        with
        [
            _Ty=std::string
        ]
Target //mediapipe_api:mediapipe_desktop failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 14.800s, Critical Path: 11.79s
INFO: 434 processes: 202 internal, 232 local.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "build.py", line 392, in <module>
    Argument().command().run()
  File "build.py", line 135, in run
    self._run_command(self._build_desktop_commands())
  File "build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "c:\users\arham\appdata\local\programs\python\python37\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bazel', '--output_user_root', 'C:/_bzl', 'build', '-c', 'opt', '--action_env', 'PYTHON_BIN_PATH=C://Users//arham//Documents//extras//mediapipe//env//Scripts//python.exe', '--define', 'MEDIAPIPE_DISABLE_GPU=1', '--@opencv//:switch=local', '//mediapipe_api:mediapipe_desktop']' returned non-zero exit status 1.
```

**Additional context**
Also tried all solutions from issue: #145 .

**Comment by homuler** [comment]
To build native libraries, Microsoft Visual C++ 2019 is required, not 2017.
https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows

**Comment by Arham-Aalam** [comment]
2019 worked fine, Thanks.
