### ISSUE TITLE
subprocess.CalledProcessError: Command '['bazel', 'build', '-c', 'opt', '//mediapipe_api:mediapipe_proto_srcs']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by Michahial** [homuler/MediaPipeUnityPlugin#230]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): Windows
- Target (e.g. desktop cpu, android arm64):: desktop CPU
- Bazel version: 4.1.0
- Python version:: 3.9
- GCC/G++ version: VC 2019
- Unity version: 2020.3.13f
- Android NDK version (if building for Android):
- Xcode version (if building for iOS):

**Describe the problem**

I am not able to compile 

PS C:\Users\holos\Downloads\MediaPipeUnityPlugin> python build.py build --desktop cpu --include_opencv_libs -v
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel build -c opt //mediapipe_api:mediapipe_proto_srcs`
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
ERROR: Skipping '/mediapipe_api:mediapipe_proto_srcs': not a valid absolute pattern (absolute target patterns must start with exactly two slashes): '/mediapipe_api:mediapipe_proto_srcs'
ERROR: not a valid absolute pattern (absolute target patterns must start with exactly two slashes): '/mediapipe_api:mediapipe_proto_srcs'
INFO: Elapsed time: 0.148s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
Traceback (most recent call last):
  File "/c/Users/holos/Downloads/MediaPipeUnityPlugin/build.py", line 392, in <module>
    Argument().command().run()
  File "/c/Users/holos/Downloads/MediaPipeUnityPlugin/build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "/c/Users/holos/Downloads/MediaPipeUnityPlugin/build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', 'build', '-c', 'opt', '//mediapipe_api:mediapipe_proto_srcs']' returned non-zero exit status 1.

**Steps to reproduce the issue**
Provide the exact sequence of commands / steps that you executed before running into the problem.

**Full logs**

**Additional context**

**Comment by Michahial** [comment]
@homuler

**Comment by Michahial** [comment]
Got it working Using windows Docker
