### ISSUE TITLE
Windows Build - streaming_buffer.h(352): error C2244: 'mediapipe::StreamingBuffer::AddData': unable to match function definition to an existing declaration

### ISSUE THREAD

**Issue by FUBAR2077** [homuler/MediaPipeUnityPlugin#265]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): Microsoft Windows [Version 10.0.19042.1165]
- Target (e.g. desktop cpu, android arm64): desktop CPU
- Bazel version: 4.2.0
- Python version: 3.9.6
- GCC/G++ version: -
- Unity version:  -
- Android NDK version (if building for Android): -
- Xcode version (if building for iOS): -

**Describe the problem**
I am building with command:
`python build.py build --desktop cpu --include_opencv_libs -v`

but after 263 seconds build encounters an error:

> ERROR: C:/_bzl/3qov6ivw/external/com_google_mediapipe/mediapipe/calculators/video/BUILD:256:11: Compiling mediapipe/calculators/video/motion_analysis_calculator.cc failed: (Exit 2): cl.exe failed: error executing command C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE ... (remaining 52 argument(s) skipped)
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(352): error C2244: 'mediapipe::StreamingBuffer::AddData': unable to match function definition to an existing declaration

**Steps to reproduce the issue**
I have an environment setup as in instructions with environmental variables setup as well:
![image](https://user-images.githubusercontent.com/4373019/131809945-7795db04-3977-4b24-86ee-5504c9042dce.png)

**Full logs**
```
ERROR: C:/_bzl/3qov6ivw/external/com_google_mediapipe/mediapipe/calculators/video/BUILD:256:11: Compiling mediapipe/calculators/video/motion_analysis_calculator.cc failed: (Exit 2): cl.exe failed: error executing command C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE ... (remaining 52 argument(s) skipped)
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(352): error C2244: 'mediapipe::StreamingBuffer::AddData': unable to match function definition to an existing declaration
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(351): note: see declaration of 'mediapipe::StreamingBuffer::AddData'
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(352): note: definition
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(352): note: 'void mediapipe::StreamingBuffer::AddData(const std::vector<std::string,std::allocator<_Ty>> &,std::unique_ptr<Types,std::default_delete<Types>>...)'
        with
        [
            _Ty=std::string
        ]
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(352): note: existing declarations
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(352): note: 'void mediapipe::StreamingBuffer::AddData(const std::vector<std::string,std::allocator<_Ty>> &,std::unique_ptr<Types,std::default_delete<Types>>...)'
        with
        [
            _Ty=std::string
        ]
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(369): error C2244: 'mediapipe::StreamingBuffer::AddDataImpl': unable to match function definition to an existing declaration
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(367): note: see declaration of 'mediapipe::StreamingBuffer::AddDataImpl'
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(369): note: definition
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(369): note: 'void mediapipe::StreamingBuffer::AddDataImpl(const std::vector<std::string,std::allocator<_Ty>> &,std::unique_ptr<_Ty,std::default_delete<_Ty>>,std::unique_ptr<Pointers,std::default_delete<Pointers>>...)'
        with
        [
            _Ty=std::string
        ]
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(369): note: existing declarations
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(369): note: 'void mediapipe::StreamingBuffer::AddDataImpl(const std::vector<std::string,std::allocator<_Ty>> &)'
        with
        [
            _Ty=std::string
        ]
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(369): note: 'void mediapipe::StreamingBuffer::AddDataImpl(const std::vector<std::string,std::allocator<_Ty>> &,std::unique_ptr<_Ty,std::default_delete<_Ty>>,std::unique_ptr<Pointers,std::default_delete<Pointers>>...)'
        with
        [
            _Ty=std::string
        ]
Target //mediapipe_api:mediapipe_desktop failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 263.777s, Critical Path: 167.74s
INFO: 2596 processes: 216 internal, 2380 local.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "D:\Projects_AL\00_Tests\MediaPipeUnityPlugin\build.py", line 392, in <module>
    Argument().command().run()
  File "D:\Projects_AL\00_Tests\MediaPipeUnityPlugin\build.py", line 135, in run
    self._run_command(self._build_desktop_commands())
  File "D:\Projects_AL\00_Tests\MediaPipeUnityPlugin\build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--output_user_root', 'C:/_bzl', 'build', '-c', 'opt', '--action_env', 'PYTHON_BIN_PATH=C://Python39//python.exe', '--define', 'MEDIAPIPE_DISABLE_GPU=1', '--@opencv//:switch=local', '//mediapipe_api:mediapipe_desktop']' returned non-zero exit status 1.
```

**Additional context**
It's really important for me that I run this unity plugin example on windows @homuler I would be grateful for quick response. I've tried docker build but I don't really know docker good enough to overcome issues I encounter there.

**Comment by FUBAR2077** [comment]
Made it with docker, closing :)
