### ISSUE TITLE
Linux gpu desktop failed build

### ISSUE THREAD

**Issue by Hakazaba** [homuler/MediaPipeUnityPlugin#271]
**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04
- Target: desktop gpu
- Bazel version: 4.2.1
- Python version: 3.9
- GCC/G++ version: gcc-8.4 and 7.5 installations

Linux desktop gpu fails, it seems to be trying to use opencv 2.2 though i have 3.2 installed(possibly incorrectly installed)

python3.9 build.py build --desktop gpu -v

```
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel build -c opt //mediapipe_api:mediapipe_proto_srcs`
TheStarting local Bazel server and connecting to it...
furyLN9
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
INFO: Analyzed target //mediapipe_api:mediapipe_proto_srcs (43 packages loaded, 668 targets configured).
INFO: Found 1 target...
Target //mediapipe_api:mediapipe_proto_srcs up-to-date:
  bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip
INFO: Elapsed time: 5.464s, Critical Path: 0.12s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
DEBUG (build.py): Unarchiving 'bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip' to 'build/Scripts/Protobuf'...
INFO (build.py): Built protobuf sources
INFO (build.py): Downloading protobuf dlls...
DEBUG (build.py): Running `nuget install -o .nuget -Source https://api.nuget.org/v3/index.json`
Feeds used:
  /home/benjamin/.nuget/packages/
  https://api.nuget.org/v3/index.json

All packages listed in /home/benjamin/MediaPipeUnityPlugin/packages.config are already installed.
DEBUG (build.py): Copying '.nuget/Google.Protobuf.3.15.6/lib/netstandard2.0/Google.Protobuf.dll' to 'build/Plugins/Protobuf/Google.Protobuf.dll'...
DEBUG (build.py): Changing the mode of 'build/Plugins/Protobuf/Google.Protobuf.dll'...
DEBUG (build.py): Copying '.nuget/System.Buffers.4.4.0/lib/netstandard2.0/System.Buffers.dll' to 'build/Plugins/Protobuf/System.Buffers.dll'...
DEBUG (build.py): Changing the mode of 'build/Plugins/Protobuf/System.Buffers.dll'...
DEBUG (build.py): Copying '.nuget/System.Memory.4.5.3/lib/netstandard2.0/System.Memory.dll' to 'build/Plugins/Protobuf/System.Memory.dll'...
DEBUG (build.py): Changing the mode of 'build/Plugins/Protobuf/System.Memory.dll'...
DEBUG (build.py): Copying '.nuget/System.Runtime.CompilerServices.Unsafe.4.5.2/lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll' to 'build/Plugins/Protobuf/System.Runtime.CompilerServices.Unsafe.dll'...
DEBUG (build.py): Changing the mode of 'build/Plugins/Protobuf/System.Runtime.CompilerServices.Unsafe.dll'...
INFO (build.py): Downloaded protobuf dlls
INFO (build.py): Building resource files
DEBUG (build.py): Running `bazel build -c opt //mediapipe_api:mediapipe_assets`
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
INFO: Analyzed target //mediapipe_api:mediapipe_assets (18 packages loaded, 49 targets configured).
INFO: Found 1 target...
Target //mediapipe_api:mediapipe_assets up-to-date:
  bazel-bin/mediapipe_api/mediapipe_assets.zip
INFO: Elapsed time: 1.615s, Critical Path: 0.55s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
DEBUG (build.py): Unarchiving 'bazel-bin/mediapipe_api/mediapipe_assets.zip' to 'build/Resources'...
INFO (build.py): Built resource files
INFO (build.py): Building native libraries for Desktop...
DEBUG (build.py): Running `bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 --@opencv//:switch=local //mediapipe_api:mediapipe_desktop`
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
INFO: Build option --copt has changed, discarding analysis cache.
INFO: Analyzed target //mediapipe_api:mediapipe_desktop (127 packages loaded, 8573 targets configured).
INFO: Found 1 target...
INFO: From Compiling mediapipe/calculators/tflite/tflite_inference_calculator.cc:
In file included from external/opencl_headers/CL/cl.h:32:0,
                 from external/org_tensorflow/tensorflow/lite/delegates/gpu/api.h:42,
                 from external/com_google_mediapipe/mediapipe/util/tflite/tflite_gpu_runner.h:25,
                 from external/com_google_mediapipe/mediapipe/calculators/tflite/tflite_inference_calculator.cc:45:
external/opencl_headers/CL/cl_version.h:34:104: note: #pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)
 #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)")
                                                                                                        ^
INFO: From Compiling mediapipe/calculators/tensor/inference_calculator_gl.cc:
In file included from external/opencl_headers/CL/cl.h:32:0,
                 from external/org_tensorflow/tensorflow/lite/delegates/gpu/api.h:42,
                 from external/com_google_mediapipe/mediapipe/util/tflite/tflite_gpu_runner.h:25,
                 from external/com_google_mediapipe/mediapipe/calculators/tensor/inference_calculator_gl.cc:27:
external/opencl_headers/CL/cl_version.h:34:104: note: #pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)
 #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)")
                                                                                                        ^
INFO: From Compiling tensorflow/lite/delegates/gpu/api.cc:
In file included from external/opencl_headers/CL/cl.h:32:0,
                 from external/org_tensorflow/tensorflow/lite/delegates/gpu/api.h:42,
                 from external/org_tensorflow/tensorflow/lite/delegates/gpu/api.cc:16:
external/opencl_headers/CL/cl_version.h:34:104: note: #pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)
 #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)")
                                                                                                        ^
INFO: From Compiling mediapipe/util/tflite/tflite_gpu_runner.cc:
In file included from external/opencl_headers/CL/cl.h:32:0,
                 from external/org_tensorflow/tensorflow/lite/delegates/gpu/api.h:42,
                 from external/com_google_mediapipe/mediapipe/util/tflite/tflite_gpu_runner.h:25,
                 from external/com_google_mediapipe/mediapipe/util/tflite/tflite_gpu_runner.cc:15:
external/opencl_headers/CL/cl_version.h:34:104: note: #pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)
 #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)")
                                                                                                        ^
ERROR: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/com_google_mediapipe/mediapipe/calculators/tensor/BUILD:632:11: Compiling mediapipe/calculators/tensor/image_to_tensor_converter_gl_buffer.cc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 68 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/com_google_mediapipe/mediapipe/calculators/tensor/image_to_tensor_converter_gl_buffer.cc: In member function 'virtual absl::lts_2020_09_23::StatusOr<mediapipe::Tensor> mediapipe::{anonymous}::GlProcessor::Convert(const mediapipe::Image&, const mediapipe::RotatedRect&, const mediapipe::Size&, float, float)':
external/com_google_mediapipe/mediapipe/calculators/tensor/image_to_tensor_converter_gl_buffer.cc:315:12: error: could not convert 'tensor' from 'mediapipe::Tensor' to 'absl::lts_2020_09_23::StatusOr<mediapipe::Tensor>'
     return tensor;
            ^~~~~~
external/com_google_mediapipe/mediapipe/calculators/tensor/image_to_tensor_converter_gl_buffer.cc: In function 'absl::lts_2020_09_23::StatusOr<std::unique_ptr<mediapipe::ImageToTensorConverter> > mediapipe::CreateImageToGlBufferTensorConverter(mediapipe::CalculatorContext*, bool, mediapipe::BorderMode)':
external/com_google_mediapipe/mediapipe/calculators/tensor/image_to_tensor_converter_gl_buffer.cc:341:10: error: could not convert 'result' from 'std::unique_ptr<mediapipe::{anonymous}::GlProcessor, std::default_delete<mediapipe::{anonymous}::GlProcessor> >' to 'absl::lts_2020_09_23::StatusOr<std::unique_ptr<mediapipe::ImageToTensorConverter> >'
   return result;
          ^~~~~~
Target //mediapipe_api:mediapipe_desktop failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 177.536s, Critical Path: 77.42s
INFO: 1168 processes: 140 internal, 1028 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "/home/benjamin/MediaPipeUnityPlugin/build.py", line 392, in <module>
    Argument().command().run()
  File "/home/benjamin/MediaPipeUnityPlugin/build.py", line 135, in run
    self._run_command(self._build_desktop_commands())
  File "/home/benjamin/MediaPipeUnityPlugin/build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "/usr/local/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', 'build', '-c', 'opt', '--copt', '-DMESA_EGL_NO_X11_HEADERS', '--copt', '-DEGL_NO_X11', '--@opencv//:switch=local', '//mediapipe_api:mediapipe_desktop']' returned non-zero exit status 1.

```

**Comment by homuler** [comment]
> GCC/G++ version: gcc-8.4 and 7.5 installations

This error usually occurs when you're using gcc/g++ 7.x, so I guess you may have installed gcc-8.4 but the default version is still 7.x. (cf. https://github.com/google/mediapipe/issues/1733)

I recommend you use [Docker](https://github.com/homuler/MediaPipeUnityPlugin#docker-for-linux-experimental) as far as it works (maybe you need to use `docker/linux/x86_64/Dockerfile.ubuntu`, instead of `docker/linux/x86_64/Dockerfile`)

**Comment by Hakazaba** [comment]
I forced 8.4 using update alternaties and got this error instead

ERROR: /home/benjamin/.cache/bazel/_bazel_root/36b3aa3a33b05b5e09f60b01181d39b0/external/XNNPACK/BUILD.bazel:3803:19: Compiling src/f32-vbinary/gen/vdiv-scalar-x2.c failed: undeclared inclusion(s) in rule '@XNNPACK//:scalar_ukernels':
this rule is missing dependency declarations for the following files included by 'src/f32-vbinary/gen/vdiv-scalar-x2.c':
  '/usr/lib/gcc/x86_64-linux-gnu/8/include/stddef.h'
  '/usr/lib/gcc/x86_64-linux-gnu/8/include/stdint.h'
  '/usr/lib/gcc/x86_64-linux-gnu/8/include/stdbool.h'
Target //mediapipe_api:mediapipe_desktop failed to build


Id rather avoid using docker if i can

**Comment by homuler** [comment]
Run the following command and try again, please.
```sh
python build.py clean
```

> Id rather avoid using docker if i can

Can you tell me why?

**Comment by Hakazaba** [comment]
~/MediaPipeUnityPlugin$ python3 build.py clean
Traceback (most recent call last):
  File "build.py", line 392, in <module>
    Argument().command().run()
  File "build.py", line 360, in __init__
    build_command_parser.add_argument('--resources', action=argparse.BooleanOptionalAction, default=True)
AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'

WHen running that command

**Comment by homuler** [comment]
Well, in your case, probably the right command is `python3.9 build.py clean`.

If you don't mind, can you answer below question as well?
>>  Id rather avoid using docker if i can

> Can you tell me why?

**Comment by Hakazaba** [comment]
Ok after clean it the build completed. I'm avoiding docker because after setting up docker to run a discourse forum years ago without being very knowledgeable about how years ago and then having trouble figuring out how to interact with it and eventually losing all of the data involved due to trusting someone i shouldn't have to run it on as a server.... Well, that stuff mostly isn't relevant to docker, but i'm trying to get across a fairly irrational aversion. 

That and i formatted this pc specifically to run mediapipe and am worried if things that ill need to be interacting with while end up locked in docker, and maybe there could be a performance cost by having whatever data being transferred two and from. While im kinda an idiot who doesn't know how it works, i realize. Thats the kinda worries i have around it

**Comment by homuler** [comment]
> maybe there could be a performance cost by having whatever data being transferred two and from

You're right that there is a performance cost to using Docker, but it's probably much smaller than you might imagine.
Also, in this project, Docker is **only used to build native libraries**, and the built libraries are copied to the host machine. That is, there is **no overhead at all after the build**, such as when you're using UnityEditor.
Even if you make a mistake and lose the data, it will only cause the native libraries to disappear (does not affect your Unity project) and you can just build them again.

Not if you need to build native libraries over and over again, but if you just need to build them once, hitting 3 commands and waiting for it to complete is much more efficient than fighting with errors for hours.

There are similar issues being created on an ongoing basis, and frankly, I don't want to spend my time supporting build issues that wouldn't occur with Docker (however, there are cases where Docker does not work).

**Comment by Hakazaba** [comment]
Fair enough, you could probably encourage people to use it more by labeling it as (preferred) instead of (experimental) - which implies less support
