### ISSUE TITLE
Windows build path issue

### ISSUE THREAD

**Issue by AbdallahKATAIE** [homuler/MediaPipeUnityPlugin#273]
**System information**
- OS Platform and Distribution : Windows 10 Home
- Target: desktop cpu, android arm64
- Bazel version: 4.2.1
- Python version: 3.9.6
- Unity version:2020.3.8f1

**After following the steps for the windows UnityEditor installation process, I ran the build command and it gave me this error :**

**Steps to reproduce the issue**
cd C:\Users\katai\Downloads\MediaPipeUnityPlugin-master
set PYTHON_BIN_PATH=C:\Users\katai\AppData\Local\Programs\Python\Python39-32
python build.py build --desktop cpu --include_opencv_libs -v

Error logs :

```
C:\Users\katai\Downloads\MediaPipeUnityPlugin-master>python build.py build --desktop cpu --include_opencv_libs -v
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH=C://Users//katai//AppData//Local//Programs//Python//Python39-32 //mediapipe_api:mediapipe_proto_srcs`
DEBUG: C:/_bzl/l75leooy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/l75leooy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/l75leooy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/l75leooy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/l75leooy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/l75leooy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/l75leooy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/l75leooy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/l75leooy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: C:/_bzl/l75leooy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: C:/_bzl/l75leooy/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
INFO: Build options --action_env and --compilation_mode have changed, discarding analysis cache.
INFO: Repository rules_python instantiated at:
  C:/users/katai/downloads/mediapipeunityplugin-master/WORKSPACE:35:23: in <toplevel>
  C:/_bzl/l75leooy/external/rules_pkg/deps.bzl:33:10: in rules_pkg_dependencies
  C:/_bzl/l75leooy/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule git_repository defined at:
  C:/_bzl/l75leooy/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'rules_python':
   Traceback (most recent call last):
        File "C:/_bzl/l75leooy/external/bazel_tools/tools/build_defs/repo/git.bzl", line 181, column 30, in _git_repository_implementation
                update = _clone_or_update(ctx)
        File "C:/_bzl/l75leooy/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update
                git_ = git_repo(ctx, directory)
        File "C:/_bzl/l75leooy/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
                _update(ctx, git_repo)
        File "C:/_bzl/l75leooy/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, column 9, in _update
                init(ctx, git_repo)
        File "C:/_bzl/l75leooy/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 118, column 15, in init
                _error(ctx.name, cl, st.stderr)
        File "C:/_bzl/l75leooy/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 190, column 9, in _error
                fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git init C:/_bzl/l75leooy/external/rules_python' while working with @rules_python:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("git" init C:/_bzl/l75leooy/external/rules_python): The system cannot find the file specified.
 (error: 2)
ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/_bzl/l75leooy/external/bazel_tools/tools/build_defs/repo/git.bzl", line 181, column 30, in _git_repository_implementation
                update = _clone_or_update(ctx)
        File "C:/_bzl/l75leooy/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update
                git_ = git_repo(ctx, directory)
        File "C:/_bzl/l75leooy/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
                _update(ctx, git_repo)
        File "C:/_bzl/l75leooy/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, column 9, in _update
                init(ctx, git_repo)
        File "C:/_bzl/l75leooy/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 118, column 15, in init
                _error(ctx.name, cl, st.stderr)
        File "C:/_bzl/l75leooy/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 190, column 9, in _error
                fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git init C:/_bzl/l75leooy/external/rules_python' while working with @rules_python:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("git" init C:/_bzl/l75leooy/external/rules_python): The system cannot find the file specified.
 (error: 2)
ERROR: C:/users/katai/downloads/mediapipeunityplugin-master/mediapipe_api/BUILD:173:8: //mediapipe_api:mediapipe_proto_srcs depends on @rules_pkg//:build_zip in repository @rules_pkg which failed to fetch. no such package '@rules_python//python': error running 'git init C:/_bzl/l75leooy/external/rules_python' while working with @rules_python:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("git" init C:/_bzl/l75leooy/external/rules_python): The system cannot find the file specified.
 (error: 2)
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.543s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (10 packages loaded, 10 targets configured)
    currently loading: @rules_pkg//
Traceback (most recent call last):
  File "C:\Users\katai\Downloads\MediaPipeUnityPlugin-master\build.py", line 392, in <module>
    Argument().command().run()
  File "C:\Users\katai\Downloads\MediaPipeUnityPlugin-master\build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\Users\katai\Downloads\MediaPipeUnityPlugin-master\build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\Users\katai\AppData\Local\Programs\Python\Python39-32\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--output_user_root', 'C:/_bzl', 'build', '-c', 'opt', '--action_env', 'PYTHON_BIN_PATH=C://Users//katai//AppData//Local//Programs//Python//Python39-32', '//mediapipe_api:mediapipe_proto_srcs']' returned non-zero exit status 1.
```

**Comment by homuler** [comment]
```txt
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("git" init C:/_bzl/l75leooy/external/rules_python): The system cannot find the file specified.
 (error: 2)
ERROR: C:/users/katai/downloads/mediapipeunityplugin-master/mediapipe_api/BUILD:173:8: //mediapipe_api:mediapipe_proto_srcs depends on @rules_pkg//:build_zip in repository @rules_pkg which failed to fetch. no such package '@rules_python//python': error running 'git init C:/_bzl/l75leooy/external/rules_python' while working with @rules_python:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("git" init C:/_bzl/l75leooy/external/rules_python): The system cannot find the file specified.
 (error: 2)
```
This means `git` command is not found.
See https://github.com/homuler/MediaPipeUnityPlugin/issues/262#issuecomment-909764639

**Comment by AbdallahKATAIE** [comment]
I just tried "git version" and it gave me : `git version 2.33.0`
I also did set to PATH
![image](https://user-images.githubusercontent.com/49809099/132325966-6aedec4b-5ddd-43b1-a3ed-c5bfdc342075.png)

**Comment by AbdallahKATAIE** [comment]
System information

OS Platform and Distribution : Windows 10 Home
Target: desktop cpu, android arm64
Bazel version: 4.2.1
Python version: 3.9.6
Unity version:2020.3.8f1

I re-installed everything again from scratch by following your guide on the windows Desktop/UnityEditor installation process, I ran the build command and it gave me this error.

Steps to reproduce the issue
cd C:\Users\katai\Downloads\MediaPipeUnityPlugin-master
set PYTHON_BIN_PATH=C:\Users\katai\AppData\Local\Programs\Python\Python39-32\python.exe
python build.py build --desktop cpu --include_opencv_libs -v

Error logs :

```
C:\Users\katai\Downloads\MediaPipeUnityPlugin-master>python build.py build --desktop cpu --include_opencv_libs -v
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH=C://Users//katai//AppData//Local//Programs//Python//Python39-32//python.exe //mediapipe_api:mediapipe_proto_srcs`
DEBUG: C:/_bzl/l75leooy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/l75leooy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/l75leooy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/l75leooy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/l75leooy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/l75leooy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/l75leooy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/l75leooy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/l75leooy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: C:/_bzl/l75leooy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: C:/_bzl/l75leooy/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
INFO: Repository local_config_cc instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:368:13: in <toplevel>
  C:/_bzl/l75leooy/external/bazel_tools/tools/cpp/cc_configure.bzl:184:16: in cc_configure
Repository rule cc_autoconf defined at:
  C:/_bzl/l75leooy/external/bazel_tools/tools/cpp/cc_configure.bzl:145:30: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cc':
   Traceback (most recent call last):
        File "C:/_bzl/l75leooy/external/bazel_tools/tools/cpp/cc_configure.bzl", line 122, column 36, in cc_autoconf_impl
                configure_windows_toolchain(repository_ctx)
        File "C:/_bzl/l75leooy/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 784, column 35, in configure_windows_toolchain
                msvc_vars_x64 = _get_msvc_vars(repository_ctx, paths, "x64")
        File "C:/_bzl/l75leooy/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 632, column 32, in _get_msvc_vars
                env = setup_vc_env_vars(repository_ctx, vc_path)
        File "C:/_bzl/l75leooy/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 387, column 24, in setup_vc_env_vars
                _check_env_vars(env_map, cmd, expected = envvars)
        File "C:/_bzl/l75leooy/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 393, column 32, in _check_env_vars
                auto_configure_fail(
        File "C:/_bzl/l75leooy/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, column 9, in auto_configure_fail
                fail("\n%sAuto-Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail:
Auto-Configuration Error: Setting up VC environment variables failed, INCLUDE is not set by the following command:
    "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\VCVARSALL.BAT" amd64 C:\Users\katai\Downloads\Windows Kits\10\WindowsSDK -vcvars_ver=14.29.30133
ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/_bzl/l75leooy/external/bazel_tools/tools/cpp/cc_configure.bzl", line 122, column 36, in cc_autoconf_impl
                configure_windows_toolchain(repository_ctx)
        File "C:/_bzl/l75leooy/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 784, column 35, in configure_windows_toolchain
                msvc_vars_x64 = _get_msvc_vars(repository_ctx, paths, "x64")
        File "C:/_bzl/l75leooy/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 632, column 32, in _get_msvc_vars
                env = setup_vc_env_vars(repository_ctx, vc_path)
        File "C:/_bzl/l75leooy/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 387, column 24, in setup_vc_env_vars
                _check_env_vars(env_map, cmd, expected = envvars)
        File "C:/_bzl/l75leooy/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 393, column 32, in _check_env_vars
                auto_configure_fail(
        File "C:/_bzl/l75leooy/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, column 9, in auto_configure_fail
                fail("\n%sAuto-Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail:
Auto-Configuration Error: Setting up VC environment variables failed, INCLUDE is not set by the following command:
    "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\VCVARSALL.BAT" amd64 C:\Users\katai\Downloads\Windows Kits\10\WindowsSDK -vcvars_ver=14.29.30133
DEBUG: Rule 'rules_python' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1564776078 -0400"
DEBUG: Repository rules_python instantiated at:
  C:/users/katai/downloads/mediapipeunityplugin-master/WORKSPACE:35:23: in <toplevel>
  C:/_bzl/l75leooy/external/rules_pkg/deps.bzl:33:10: in rules_pkg_dependencies
  C:/_bzl/l75leooy/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule git_repository defined at:
  C:/_bzl/l75leooy/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "86bf1c24e8f859fb5c66d931f33dc8283427e7370d2b0d178658893bcd3c49e9"
DEBUG: Repository rules_cc instantiated at:
  C:/users/katai/downloads/mediapipeunityplugin-master/WORKSPACE:78:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/l75leooy/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: C:/_bzl/l75leooy/external/rules_pkg/BUILD:68:10: @rules_pkg//:build_zip depends on @local_config_cc//:cc-compiler-x64_windows in repository @local_config_cc which failed to fetch. no such package '@local_config_cc//':
Auto-Configuration Error: Setting up VC environment variables failed, INCLUDE is not set by the following command:
    "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\VCVARSALL.BAT" amd64 C:\Users\katai\Downloads\Windows Kits\10\WindowsSDK -vcvars_ver=14.29.30133
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.452s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: @com_google_mediapipe//mediapipe/framework ... (6 packages)
    Fetching @com_google_protobuf; fetching
    Fetching ...otobuf; Extracting C:/_bzl/l75leooy/external/com_google_protobuf/temp11696971243794458306/v3.11.4.tar.\
gz
Traceback (most recent call last):
  File "C:\Users\katai\Downloads\MediaPipeUnityPlugin-master\build.py", line 392, in <module>
    Argument().command().run()
  File "C:\Users\katai\Downloads\MediaPipeUnityPlugin-master\build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\Users\katai\Downloads\MediaPipeUnityPlugin-master\build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\Users\katai\AppData\Local\Programs\Python\Python39-32\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--output_user_root', 'C:/_bzl', 'build', '-c', 'opt', '--action_env', 'PYTHON_BIN_PATH=C://Users//katai//AppData//Local//Programs//Python//Python39-32//python.exe', '//mediapipe_api:mediapipe_proto_srcs']' returned non-zero exit status 1.
```

**Comment by AbdallahKATAIE** [comment]
Update, I changed the VC location and it started building properly but stopped all of a sudden here:

```
external/com_google_protobuf/src\google/protobuf/util/time_util.h(46): fatal error C1083: Impossible d'ouvrir le fichier include : 'winsock2.h' : No such file or directory
Target //mediapipe_api:mediapipe_proto_srcs failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 25.907s, Critical Path: 20.38s
INFO: 169 processes: 139 internal, 30 local.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "C:\Users\katai\Downloads\MediaPipeUnityPlugin-master\build.py", line 392, in <module>
    Argument().command().run()
  File "C:\Users\katai\Downloads\MediaPipeUnityPlugin-master\build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\Users\katai\Downloads\MediaPipeUnityPlugin-master\build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\Users\katai\AppData\Local\Programs\Python\Python39-32\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--output_user_root', 'C:/_bzl', 'build', '-c', 'opt', '--action_env', 'PYTHON_BIN_PATH=C://Users//katai//AppData//Local//Programs//Python//Python39-32//python.exe', '//mediapipe_api:mediapipe_proto_srcs']' returned non-zero exit status 1.

```


it says fatal error, the folder "winsock2.h" can't be opened : no such file or directory


what am I supposed to do ?

**Comment by AbdallahKATAIE** [comment]
Everything compiled well after I set the WinSDK version to : 10.0.19041.0
Please use this command if you got stuck for the same 2 reasons mentioned above:


`set BAZEL_WINSDK_FULL_VERSION=10.0.19041.0`
