### ISSUE TITLE
Docker for Windows Android Build Error

### ISSUE THREAD

**Issue by BenjaminMassey** [homuler/MediaPipeUnityPlugin#284]
**System information**

- OS Platform and Distribution: Windows 10 Pro
- Target: Android arm64
- Bazel version: 4.2.1
- Python version: 3.9.7
- GCC/G++ version: 10.3.0
- Unity version: 2020.3.8f1

**Describe the problem**

Failure during building for Android under Docker for Windows.

**Steps to reproduce the issue**

I have installed the plugin for Windows successfully: runs great through the Unity editor. However, while Unity builds an Android APK successfully, no camera imaging comes up when run (no crashing and scene UI is visible, but camera does not display).

In hopes to fix this, I'm going through the readme's tutorial steps under "Docker for Windows (experimental) > Android" because of the "You cannot build native libraries for Android on Windows 10, so use Docker for Windows instead" comment.

I have successfully completed the first 3/4 steps, but I have run into failure towards the end of the "python build.py build --android arm64 -v" step. I have tried my best to debug this, but have come up short with a solution.

**Error Log**

```
ERROR: /home/mediapipe/mediapipe_api/framework/BUILD:106:17: Executing genrule //mediapipe_api/framework:packet_generator_cs failed: (Exit 127): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/bin/bash: line 1: $'\r': command not found
Target //mediapipe_api:mediapipe_proto_srcs failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 206.987s, Critical Path: 90.12s
INFO: 202 processes: 25 internal, 177 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "/home/mediapipe/build.py", line 392, in <module>
    Argument().command().run()
  File "/home/mediapipe/build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "/home/mediapipe/build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', 'build', '-c', 'opt', '//mediapipe_api:mediapipe_proto_srcs']' returned non-zero exit status 1.
```

**Full logs**

```
C:\WINDOWS\system32>cd C:/Users/User/sofiqeunity/Sofiqe

C:\Users\User\sofiqeunity\Sofiqe>docker run --cpus=16 --memory=8192m ^
More?     --mount type=bind,src=%CD%\Packages,dst=/home/mediapipe/Packages ^
More?     -it mediapipe_unity:linux
[mediapipe@6ccfd9a7447a ~]$ python build.py build --android arm64 -v
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel build -c opt //mediapipe_api:mediapipe_proto_srcs`
2021/09/14 23:40:43 Downloading https://releases.bazel.build/4.2.1/release/bazel-4.2.1-linux-x86_64...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/tensorflow/runtime/archive/44c890cd46fd9aad2b3bf4b13c5f36d8cff795c3.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
DEBUG: Rule 'rules_python' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1564776078 -0400"
DEBUG: Repository rules_python instantiated at:
  /home/mediapipe/WORKSPACE:35:23: in <toplevel>
  /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/rules_pkg/deps.bzl:33:10: in rules_pkg_dependencies
  /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule git_repository defined at:
  /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
INFO: SHA256 (https://github.com/bazelbuild/rules_cc/archive/main.zip) = 86bf1c24e8f859fb5c66d931f33dc8283427e7370d2b0d178658893bcd3c49e9
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "86bf1c24e8f859fb5c66d931f33dc8283427e7370d2b0d178658893bcd3c49e9"
DEBUG: Repository rules_cc instantiated at:
  /home/mediapipe/WORKSPACE:78:13: in <toplevel>
Repository rule http_archive defined at:
  /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Analyzed target //mediapipe_api:mediapipe_proto_srcs (44 packages loaded, 676 targets configured).
INFO: Found 1 target...
INFO: From Compiling src/google/protobuf/generated_message_reflection.cc [for host]:
external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc: In member function 'void google::protobuf::Reflection::SwapOneofField(google::protobuf::Message*, google::protobuf::Message*, const google::protobuf::OneofDescriptor*) const':
external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc:2131:37: warning: 'temp_bool' may be used uninitialized in this function [-Wmaybe-uninitialized]
 2131 |   *MutableRaw<Type>(message, field) = value;
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc:496:8: note: 'temp_bool' was declared here
  496 |   bool temp_bool;
      |        ^~~~~~~~~
external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc:2131:37: warning: 'temp_int64' may be used uninitialized in this function [-Wmaybe-uninitialized]
 2131 |   *MutableRaw<Type>(message, field) = value;
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc:491:9: note: 'temp_int64' was declared here
  491 |   int64 temp_int64;
      |         ^~~~~~~~~~
ERROR: /home/mediapipe/mediapipe_api/framework/BUILD:106:17: Executing genrule //mediapipe_api/framework:packet_generator_cs failed: (Exit 127): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/bin/bash: line 1: $'\r': command not found
Target //mediapipe_api:mediapipe_proto_srcs failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 206.987s, Critical Path: 90.12s
INFO: 202 processes: 25 internal, 177 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "/home/mediapipe/build.py", line 392, in <module>
    Argument().command().run()
  File "/home/mediapipe/build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "/home/mediapipe/build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', 'build', '-c', 'opt', '//mediapipe_api:mediapipe_proto_srcs']' returned non-zero exit status 1.
```

**Additional context**

If I comment out this particular part of build.py, then it fails in an extremely similar way with "mediapipe_android.aar". If I comment this out, then it completes, so I believe these to be the only two parts that fail.

I really appreciate any help in advance, and let me know if I can send anything else useful.

**Comment by homuler** [comment]
Could you please check your `autocrlf` settings?
https://github.com/homuler/MediaPipeUnityPlugin/issues/172#issuecomment-843014178

**Comment by BenjaminMassey** [comment]
Setting autocrlf to false like in the linked thread didn't seem to do much, but using the Ubuntu Docker container like detailed in the thread did: problem solved!

Here's specifically what solved my issue: https://github.com/homuler/MediaPipeUnityPlugin/issues/172#issuecomment-843222262

Thank you so much for your help!
