### ISSUE TITLE
Error in build android with linux docker

### ISSUE THREAD

**Issue by ali-najjar** [homuler/MediaPipeUnityPlugin#319]
**System information**
- Arch docker file in ubuntu host

**Command**

`python build.py build --opencv=cmake --android arm64 -v`

**Error Log**

bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.cc: In member function 'virtual google::protobuf::uint8* mediapipe::ProfilerConfig::_InternalSerialize(google::protobuf::uint8*, google::protobuf::io::Eps
CopyOutputStream*) const':
bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.cc:1714:41: warning: 'bool mediapipe::ProfilerConfig::enable_input_output_latency() const' is deprecated [-Wdeprecated-declarations]
 1714 |   if (this->enable_input_output_latency() != 0) {
      |                                         ^
In file included from bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.cc:4:
bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.h:2734:13: note: declared here
 2734 | inline bool ProfilerConfig::enable_input_output_latency() const {
      |             ^~~~~~~~~~~~~~
bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.cc:1781:39: warning: 'bool mediapipe::ProfilerConfig::trace_log_duration_events() const' is deprecated [-Wdeprecated-declarations]
 1781 |   if (this->trace_log_duration_events() != 0) {
      |                                       ^
In file included from bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.cc:4:
bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.h:3001:13: note: declared here
 3001 | inline bool ProfilerConfig::trace_log_duration_events() const {
      |             ^~~~~~~~~~~~~~
bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.cc: In member function 'virtual size_t mediapipe::ProfilerConfig::ByteSizeLong() const':
bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.cc:1863:41: warning: 'bool mediapipe::ProfilerConfig::enable_input_output_latency() const' is deprecated [-Wdeprecated-declarations]
 1863 |   if (this->enable_input_output_latency() != 0) {
      |                                         ^
In file included from bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.cc:4:
bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.h:2734:13: note: declared here
 2734 | inline bool ProfilerConfig::enable_input_output_latency() const {
      |             ^~~~~~~~~~~~~~
bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.cc:1918:39: warning: 'bool mediapipe::ProfilerConfig::trace_log_duration_events() const' is deprecated [-Wdeprecated-declarations]
 1918 |   if (this->trace_log_duration_events() != 0) {
      |                                       ^
In file included from bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.cc:4:
bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.h:3001:13: note: declared here
 3001 | inline bool ProfilerConfig::trace_log_duration_events() const {
      |             ^~~~~~~~~~~~~~
bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.cc: In member function 'void mediapipe::ProfilerConfig::MergeFrom(const mediapipe::ProfilerConfig&)':
bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.cc:1979:40: warning: 'bool mediapipe::ProfilerConfig::enable_input_output_latency() const' is deprecated [-Wdeprecated-declarations]
 1979 |   if (from.enable_input_output_latency() != 0) {
      |                                        ^
In file included from bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.cc:4:
bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.h:2734:13: note: declared here
 2734 | inline bool ProfilerConfig::enable_input_output_latency() const {
      |             ^~~~~~~~~~~~~~
bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.h:3001:13: note: declared here
 3001 | inline bool ProfilerConfig::trace_log_duration_events() const {
      |             ^~~~~~~~~~~~~~
bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.cc: In member function 'virtual google::protobuf::uint8* mediapipe::CalculatorGraphConfig_Node::_InternalSerialize(google::protobuf::uint8*, google::protobuf::io::EpsCopyOutputStream*) const':
bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.cc:2575:33: warning: 'bool mediapipe::CalculatorGraphConfig_Node::has_profiler_config() const' is deprecated [-Wdeprecated-declarations]
 2575 |   if (this->has_profiler_config()) {
      |                                 ^
In file included from bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.cc:4:
bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.h:3855:13: note: declared here
 3855 | inline bool CalculatorGraphConfig_Node::has_profiler_config() const {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~
bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.cc: In member function 'virtual size_t mediapipe::CalculatorGraphConfig_Node::ByteSizeLong() const':
bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.cc:2711:33: warning: 'bool mediapipe::CalculatorGraphConfig_Node::has_profiler_config() const' is deprecated [-Wdeprecated-declarations]
 2711 |   if (this->has_profiler_config()) {
      |                                 ^
In file included from bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.cc:4:
bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.h:3855:13: note: declared here
 3855 | inline bool CalculatorGraphConfig_Node::has_profiler_config() const {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~
bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.cc: In member function 'void mediapipe::CalculatorGraphConfig_Node::MergeFrom(const mediapipe::CalculatorGraphConfig_Node&)':
bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.cc:2797:32: warning: 'bool mediapipe::CalculatorGraphConfig_Node::has_profiler_config() const' is deprecated [-Wdeprecated-declarations]
 2797 |   if (from.has_profiler_config()) {
      |                                ^
In file included from bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.cc:4:
bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/calculator.pb.h:3855:13: note: declared here
 3855 | inline bool CalculatorGraphConfig_Node::has_profiler_config() const {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~
INFO: From Executing genrule @com_google_mediapipe//mediapipe/modules/palm_detection:palm_detection_gpu_graph:
[libprotobuf WARNING external/com_google_protobuf/src/google/protobuf/text_format.cc:324] Warning parsing text-format mediapipe.CalculatorGraphConfig: 60:5: text format contains deprecated field "use_gpu"
[2,908 / 5,326] 128 actions, 2 running
    Compiling mediapipe/modules/objectron/calculators/decoder.cc; 1789s processwrapper-sandbox
    Compiling mediapipe/calculators/core/split_vector_calculator.cc; 1779s processwrapper-sandbox
    [Sched] Desugaring .../homuler/mediapipe/libmediapipe_android_android_lib.jar for Android; 2712s
    [Sched] Desugaring .../homuler/mediapipe/mediapipe_android_dummy_app_resources.jar for Android; 2672s
    [Sched] @maven//:androidx_loader_loader; 2544s
    [Sched] @maven//:androidx_legacy_legacy_support_core_utils; 2501s
    [Sched] @maven//:androidx_vectordrawable_vectordrawable_animated; 2500s
    [Sched] @maven//:androidx_coordinatorlayout_coordinatorlayout; 2494s ...

Server terminated abruptly (error code: 14, error message: 'Socket closed', log file: '/home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/server/jvm.out')

Traceback (most recent call last):
  File "/home/mediapipe/build.py", line 444, in <module>
    Argument().command().run()
  File "/home/mediapipe/build.py", line 159, in run
    self._run_command(self._build_android_commands())
  File "/home/mediapipe/build.py", line 52, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel build -c opt --config=android_arm64 //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android' returned non-zero exit status 37.+

**Comment by ali-najjar** [comment]
The '/home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/server/jvm.out' file is empty (I think because it's in container)

**Comment by homuler** [comment]
I think your machine is running out of memory.
