### ISSUE TITLE
Failed to connect to github.com port 443: Timed out

### ISSUE THREAD

**Issue by SYl110607** [homuler/MediapipeUnityPlugin#324]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2):window10
- Target (e.g. desktop cpu, android arm64):desktop cpu
- Bazel version:3.7.2
- Python version:3.9.7
- Unity version:2020.3.16

**Describe the problem**
When I run the command:python build.py build --desktop cpu --include_opencv_libs -v,it can not build successfully
**Steps to reproduce the issue**
python build.py build --desktop cpu --include_opencv_libs -v

**Full logs**
E:\UnityProJects\MediaPipeUnityPlugin-master>python build.py build --desktop cpu --include_opencv_libs -v
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --host_jvm_args "-DsocksProxyHost=127.0.0.1" --host_jvm_args "-DsocksProxyPort=7890" --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//shengyilai//AppData//Local//Programs//Python//Python39//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION //mediapipe_api:mediapipe_proto_srcs`
WARNING: Running Bazel server needs to be killed, because the startup options are different.
Starting local Bazel server and connecting to it...
DEBUG: C:/_bzl/sqzb2w22/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/sqzb2w22/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/sqzb2w22/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/sqzb2w22/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/sqzb2w22/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/sqzb2w22/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/sqzb2w22/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/sqzb2w22/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/sqzb2w22/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: C:/_bzl/sqzb2w22/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: C:/_bzl/sqzb2w22/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
INFO: Repository rules_python instantiated at:
  E:/unityprojects/mediapipeunityplugin-master/WORKSPACE:41:23: in <toplevel>
  C:/_bzl/sqzb2w22/external/rules_pkg/deps.bzl:33:10: in rules_pkg_dependencies
  C:/_bzl/sqzb2w22/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule git_repository defined at:
  C:/_bzl/sqzb2w22/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'rules_python':
   Traceback (most recent call last):
        File "C:/_bzl/sqzb2w22/external/bazel_tools/tools/build_defs/repo/git.bzl", line 181, column 30, in _git_repository_implementation
                update = _clone_or_update(ctx)
        File "C:/_bzl/sqzb2w22/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update
                git_ = git_repo(ctx, directory)
        File "C:/_bzl/sqzb2w22/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
                _update(ctx, git_repo)
        File "C:/_bzl/sqzb2w22/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 103, column 10, in _update
                fetch(ctx, git_repo)
        File "C:/_bzl/sqzb2w22/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 136, column 13, in fetch
                _git(
        File "C:/_bzl/sqzb2w22/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 169, column 15, in _git
                _error(ctx.name, start + list(args), st.stderr)
        File "C:/_bzl/sqzb2w22/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 190, column 9, in _error
                fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @rules_python:
fatal: unable to access 'https://github.com/bazelbuild/rules_python.git/': Failed to connect to github.com port 443: Timed out
ERROR: E:/unityprojects/mediapipeunityplugin-master/mediapipe_api/BUILD:175:8: //mediapipe_api:mediapipe_proto_srcs depends on @rules_pkg//:build_zip in repository @rules_pkg which failed to fetch. no such package '@rules_python//python': error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @rules_python:
fatal: unable to access 'https://github.com/bazelbuild/rules_python.git/': Failed to connect to github.com port 443: Timed out
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: Analysis failed
INFO: Elapsed time: 268.110s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (12 packages loaded, 10 targets configured)
    currently loading: @rules_pkg//
Traceback (most recent call last):
  File "E:\UnityProJects\MediaPipeUnityPlugin-master\build.py", line 445, in <module>
    Argument().command().run()
  File "E:\UnityProJects\MediaPipeUnityPlugin-master\build.py", line 112, in run
    self._run_command(self._build_proto_srcs_commands())
  File "E:\UnityProJects\MediaPipeUnityPlugin-master\build.py", line 52, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Users\shengyilai\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --host_jvm_args "-DsocksProxyHost=127.0.0.1" --host_jvm_args "-DsocksProxyPort=7890" --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//shengyilai//AppData//Local//Programs//Python//Python39//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 1.
**Additional context**
I have followed mediapipe's installation guide and install MSYS2, Python, Visual C++ Build Tools 2019, WinSDK and Bazel(step1 ~ step6) and build the example successfully,and i update the commands ['bazel'] with ["bazel", "--host_jvm_args", "\"-DsocksProxyHost=127.0.0.1\"", "--host_jvm_args", "\"-DsocksProxyPort=7890\""] so that it is not a proxy problem,please help,thanks.

**Comment by SYl110607** [comment]
> > Is there any way I can get the face rotation angles?
> 
> Basically, I don't want you to ask me how to use MediaPipe itself here (ask it in MediaPipe community instead), but I think you can get these values by examining the slope of the line segment connecting two specific landmarks (e.g. Left ear to Right ear, Top of the head to the tip of the chin, etc...).

Ok, thanks. I will figure it out.
