### ISSUE TITLE
Windows mediapipe_jni and docker build problem

### ISSUE THREAD

**Issue by AbdallahKATAIE** [homuler/MediaPipeUnityPlugin#349]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): Windows 10
- Target (e.g. desktop cpu, android arm64): android arm64
- Bazel version: 4.2.1
- Python version: 3.9.0
- Unity version: 2020.3.8f1
- Android NDK version (if building for Android): 19.0.5232133

**Describe the problem**
I need to build the new update for Android because I had the 90° detection orientation problem with the latest plugin version.

**First build**
So I tried to build using https://github.com/homuler/MediaPipeUnityPlugin#windows even though I want to build the unity project on Android but it gave me this error :

![image](https://user-images.githubusercontent.com/49809099/141123826-fee00bb3-746b-4fd0-9ac7-a0b971f6af67.png)

I followed these issues https://github.com/homuler/MediaPipeUnityPlugin/issues/269 and https://github.com/homuler/MediaPipeUnityPlugin/issues/171#issuecomment-850154795 to repair it but nothing changed 

**2nd Build**
so I decided to go with the docker build (since I want android in the end)

**Steps to reproduce the issue**
First I switched to Linux Containers, then :
`docker build -t mediapipe_unity:linux . -f docker/linux/x86_64/Dockerfile`
```
docker run --cpus=8 --memory=8192m ^
    --mount type=bind,src=%CD%\Packages,dst=/home/mediapipe/Packages ^
    --mount type=bind,src=%CD%\Assets,dst=/home/mediapipe/Assets ^
    -it mediapipe_unity:linux

```
(worked fine)
then 

`python build.py build --android arm64 -v`
So I got this message (couldn't get the entire log, just the error part)
**Logs**
![image](https://user-images.githubusercontent.com/49809099/141124906-6f05e10e-39b2-477b-9627-42d900e6681f.png)

**Additional context**

Should I go with my first or 2nd build if I want to run the Unity project on Android ?
And how do I resolve the issue of the chosen build ?

**Comment by naeem76** [comment]
use windows containers in docker

**Comment by homuler** [comment]
Thank you for reporting the issue.
A recent update to `unzip` seems to have broken the program.
Fixed by https://github.com/homuler/MediaPipeUnityPlugin/commit/a9edb9e8f2e8c40da7bd92376cb567fa9a59c703.

Pull the update and build Docker image again, please.

**Comment by AbdallahKATAIE** [comment]
I pulled the update and this is the result :
Building the docker gave this : 

![image](https://user-images.githubusercontent.com/49809099/141270308-cf402aa8-d649-421c-9e78-217f3cc3e17d.png)




**Inside docker Build Command :**

```
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "7e3caad112850996a9c6d78b9f7593d01c030ca50872884cad35e7caf754497c"
DEBUG: Repository rules_cc instantiated at:
  /home/mediapipe/WORKSPACE:84:13: in <toplevel>
Repository rule http_archive defined at:
  /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: Rule 'rules_python' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1564776078 -0400"
DEBUG: Repository rules_python instantiated at:
  /home/mediapipe/WORKSPACE:41:23: in <toplevel>
  /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/rules_pkg/deps.bzl:33:10: in rules_pkg_dependencies
  /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule git_repository defined at:
  /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
INFO: Repository android_tools instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:311:13: in <toplevel>
Repository rule http_archive defined at:
  /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository remotejdk11_linux instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:52:6: in <toplevel>
  /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule http_archive defined at:
  /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from https://mirror.bazel.build/openjdk/azul-zulu11.37.17-ca-jdk11.0.6/zulu11.37.17-ca-jdk11.0.6-linux_x64.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was c5420496f05bb39c7382982456b1cd58f007179cebaac570278b03b114cc1bdf but wanted 360626cc19063bc411bfed2914301b908a8f77a7919aaea007a977fa8fb3cde1
ERROR: An error occurred during the fetch of repository 'remotejdk11_linux':
   Traceback (most recent call last):
        File "/home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://mirror.bazel.build/openjdk/azul-zulu11.37.17-ca-jdk11.0.6/zulu11.37.17-ca-jdk11.0.6-linux_x64.tar.gz] to /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/remotejdk11_linux/temp7978245719865839454/zulu11.37.17-ca-jdk11.0.6-linux_x64.tar.gz: Checksum was c5420496f05bb39c7382982456b1cd58f007179cebaac570278b03b114cc1bdf but wanted 360626cc19063bc411bfed2914301b908a8f77a7919aaea007a977fa8fb3cde1
ERROR: Error fetching repository: Traceback (most recent call last):
        File "/home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://mirror.bazel.build/openjdk/azul-zulu11.37.17-ca-jdk11.0.6/zulu11.37.17-ca-jdk11.0.6-linux_x64.tar.gz] to /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/remotejdk11_linux/temp7978245719865839454/zulu11.37.17-ca-jdk11.0.6-linux_x64.tar.gz: Checksum was c5420496f05bb39c7382982456b1cd58f007179cebaac570278b03b114cc1bdf but wanted 360626cc19063bc411bfed2914301b908a8f77a7919aaea007a977fa8fb3cde1
INFO: Repository maven instantiated at:
  /home/mediapipe/WORKSPACE:389:14: in <toplevel>
  /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/rules_jvm_external/defs.bzl:105:19: in maven_install
Repository rule coursier_fetch defined at:
  /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/rules_jvm_external/coursier.bzl:1009:33: in <toplevel>
INFO: Repository opencv instantiated at:
  /home/mediapipe/WORKSPACE:235:13: in <toplevel>
Repository rule http_archive defined at:
  /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository remote_java_tools_linux instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:223:6: in <toplevel>
  /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule http_archive defined at:
  /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/bazel_tools/tools/jdk/BUILD:490:6: @bazel_tools//tools/jdk:remote_jdk11 depends on @remotejdk11_linux//:jdk in repository @remotejdk11_linux which failed to fetch. no such package '@remotejdk11_linux//': java.io.IOException: Error downloading [https://mirror.bazel.build/openjdk/azul-zulu11.37.17-ca-jdk11.0.6/zulu11.37.17-ca-jdk11.0.6-linux_x64.tar.gz] to /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/remotejdk11_linux/temp7978245719865839454/zulu11.37.17-ca-jdk11.0.6-linux_x64.tar.gz: Checksum was c5420496f05bb39c7382982456b1cd58f007179cebaac570278b03b114cc1bdf but wanted 360626cc19063bc411bfed2914301b908a8f77a7919aaea007a977fa8fb3cde1
ERROR: Analysis of target '//mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android' failed; build aborted: Analysis failed
INFO: Elapsed time: 214.008s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (18 packages loaded, 7066 targets configured)
Traceback (most recent call last):
  File "/home/mediapipe/build.py", line 444, in <module>
    Argument().command().run()
  File "/home/mediapipe/build.py", line 159, in run
    self._run_command(self._build_android_commands())
  File "/home/mediapipe/build.py", line 52, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel build -c opt --config=android_arm64 //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android' returned non-zero exit status 1.
```

**Comment by homuler** [comment]
I'm not sure without details logs, but I think it's a network error, so please give it some time and retry.
But if you can donwload `https://mirror.bazel.build/openjdk/azul-zulu11.37.17-ca-jdk11.0.6/zulu11.37.17-ca-jdk11.0.6-linux_x64.tar.gz` from your host machine, your docker container may not be able to access the host's network.
