### ISSUE TITLE
Windows build error bazel related

### ISSUE THREAD

**Issue by Yaman500iq** [homuler/MediaPipeUnityPlugin#353]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): windows 10
- Target (e.g. desktop cpu, android arm64): windows editor
- Bazel version: 4.1.0
- Python version:  3.10.0
- GCC/G++ version: 
- Unity version: Unity 2020.3.8f1 (64-bit)
- Android NDK version (if building for Android):
- Xcode version (if building for iOS):

**Describe the problem**

**Steps to reproduce the issue**
Provide the exact sequence of commands / steps that you executed before running into the problem.

C:\Users\y95s>cd C:\MediaPipeUnityPlugin-master

C:\MediaPipeUnityPlugin-master>set PYTHON_BIN_PATH=C:\Users\y95s\AppData\Local\Programs\Python\Python310\python.exe

C:\MediaPipeUnityPlugin-master>python build.py build --desktop cpu --opencv=cmake -v

**Full logs**

```
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//y95s//AppData//Local//Programs//Python//Python310//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION //mediapipe_api:mediapipe_proto_srcs`
Starting local Bazel server and connecting to it...
DEBUG: C:/_bzl/e5izyx6r/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/e5izyx6r/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/e5izyx6r/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/e5izyx6r/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/e5izyx6r/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/e5izyx6r/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/e5izyx6r/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/e5izyx6r/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/e5izyx6r/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: C:/_bzl/e5izyx6r/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: C:/_bzl/e5izyx6r/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
INFO: Repository rules_python instantiated at:
  C:/mediapipeunityplugin-master/WORKSPACE:41:23: in <toplevel>
  C:/_bzl/e5izyx6r/external/rules_pkg/deps.bzl:33:10: in rules_pkg_dependencies
  C:/_bzl/e5izyx6r/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule git_repository defined at:
  C:/_bzl/e5izyx6r/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'rules_python':
   Traceback (most recent call last):
        File "C:/_bzl/e5izyx6r/external/bazel_tools/tools/build_defs/repo/git.bzl", line 181, column 30, in _git_repository_implementation
                update = _clone_or_update(ctx)
        File "C:/_bzl/e5izyx6r/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update
                git_ = git_repo(ctx, directory)
        File "C:/_bzl/e5izyx6r/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
                _update(ctx, git_repo)
        File "C:/_bzl/e5izyx6r/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, column 9, in _update
                init(ctx, git_repo)
        File "C:/_bzl/e5izyx6r/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 118, column 15, in init
                _error(ctx.name, cl, st.stderr)
        File "C:/_bzl/e5izyx6r/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 190, column 9, in _error
                fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git init C:/_bzl/e5izyx6r/external/rules_python' while working with @rules_python:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("git" init C:/_bzl/e5izyx6r/external/rules_python): The system cannot find the file specified.
 (error: 2)
ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/_bzl/e5izyx6r/external/bazel_tools/tools/build_defs/repo/git.bzl", line 181, column 30, in _git_repository_implementation
                update = _clone_or_update(ctx)
        File "C:/_bzl/e5izyx6r/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update
                git_ = git_repo(ctx, directory)
        File "C:/_bzl/e5izyx6r/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
                _update(ctx, git_repo)
        File "C:/_bzl/e5izyx6r/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, column 9, in _update
                init(ctx, git_repo)
        File "C:/_bzl/e5izyx6r/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 118, column 15, in init
                _error(ctx.name, cl, st.stderr)
        File "C:/_bzl/e5izyx6r/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 190, column 9, in _error
                fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git init C:/_bzl/e5izyx6r/external/rules_python' while working with @rules_python:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("git" init C:/_bzl/e5izyx6r/external/rules_python): The system cannot find the file specified.
 (error: 2)
ERROR: C:/mediapipeunityplugin-master/mediapipe_api/BUILD:175:8: //mediapipe_api:mediapipe_proto_srcs depends on @rules_pkg//:build_zip in repository @rules_pkg which failed to fetch. no such package '@rules_python//python': error running 'git init C:/_bzl/e5izyx6r/external/rules_python' while working with @rules_python:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("git" init C:/_bzl/e5izyx6r/external/rules_python): The system cannot find the file specified.
 (error: 2)
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: Analysis failed
INFO: Elapsed time: 5.994s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (12 packages loaded, 10 targets configured)
    currently loading: @rules_pkg//
Traceback (most recent call last):
  File "C:\MediaPipeUnityPlugin-master\build.py", line 444, in <module>
    Argument().command().run()
  File "C:\MediaPipeUnityPlugin-master\build.py", line 112, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\MediaPipeUnityPlugin-master\build.py", line 52, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Users\y95s\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//y95s//AppData//Local//Programs//Python//Python310//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 1.

```
**Additional context**

**Comment by homuler** [comment]
Same as https://github.com/homuler/MediaPipeUnityPlugin/issues/273#issuecomment-914151894.
In addition to that, it's known that it cannot be built with Python 3.10 now, so please use Python 3.9.x instead.
https://github.com/homuler/MediaPipeUnityPlugin/issues/329
