### ISSUE TITLE
Configuration Error: --define PYTHON_BIN_PATH='D://Python//Python36//python.exe' is not executable. Is it the python binary?

### ISSUE THREAD

**Issue by DearVa** [homuler/MediaPipeUnityPlugin#57]
This error occurs when executing: make cpu PYTHON_BIN_PATH="D://Python//Python36//python.exe"
System: Windows 10

```
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/_bzl/khpdadwx/external/org_tensorflow/third_party/py/python_configure.bzl", line 209, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/_bzl/khpdadwx/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/_bzl/khpdadwx/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='D://Python//Python36//python.exe' is not executable. Is it the python binary?
ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/_bzl/khpdadwx/external/org_tensorflow/third_party/py/python_configure.bzl", line 209, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/_bzl/khpdadwx/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/_bzl/khpdadwx/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='D://Python//Python36//python.exe' is not executable. Is it the python binary?
INFO: Repository com_google_protobuf instantiated at:
  F:/sourceoffline/github/mediapipeunityplugin/c/WORKSPACE:173:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/khpdadwx/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "4fc66738a55efcc6e2195da98ea8c7f4f1d9ad42a084cadd0724c59f5c8930c0"
DEBUG: Repository rules_cc instantiated at:
  F:/sourceoffline/github/mediapipeunityplugin/c/WORKSPACE:73:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/khpdadwx/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: Rule 'rules_python' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1564776078 -0400"
DEBUG: Repository rules_python instantiated at:
  F:/sourceoffline/github/mediapipeunityplugin/c/WORKSPACE:30:23: in <toplevel>
  C:/_bzl/khpdadwx/external/rules_pkg/deps.bzl:33:10: in rules_pkg_dependencies
  C:/_bzl/khpdadwx/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule git_repository defined at:
  C:/_bzl/khpdadwx/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
ERROR: Analysis of target '//mediapipe_api:mediapipe_desktop' failed; build aborted: Configuration Error: --define PYTHON_BIN_PATH='D://Python//Python36//python.exe' is not executable. Is it the python binary?
INFO: Elapsed time: 1.263s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: @com_google_mediapipe//mediapipe/framework ... (3 packages)
Makefile:46: recipe for target 'cpu' failed
make: *** [cpu] Error 1
```

**Comment by zer0012** [comment]
me to meet this problem How did you solve it
need help plz
I Need Healing

**Comment by DearVa** [comment]
> > 我遇到这个问题 你是如何解决的 需要帮助 我需要治疗
> 
> Have you solved this problem? Can you tell me how you solved it？

已经忘记了……我似乎是单独用python跑了MediaPipe然后IPC传输给Unity
