### ISSUE TITLE
build iOS error in Mac

### ISSUE THREAD

**Issue by ehsanwwe** [homuler/MediaPipeUnityPlugin#649]
### Plugin Version or Commit ID

lasted

### Unity Version

----

### Your Host OS

Mac OS 11.1

### Target Platform

iOS

### Command Sequences

after 5 month I try again to build an iOS for my project
in the previous test I haven't any error in run Python commands

but today I got this error
can you help me what is reason of this error

### Log

```
DEBUG (build.py): Copying '.nuget/System.Buffers.4.4.0/lib/netstandard2.0/System.Buffers.dll' to 'build/Plugins/Protobuf/System.Buffers.dll'...
DEBUG (build.py): Creating 'build/Plugins/Protobuf'...
DEBUG (build.py): Changing the mode of 'build/Plugins/Protobuf/System.Buffers.dll'...
DEBUG (build.py): Copying '.nuget/Google.Protobuf.3.20.0/lib/netstandard2.0/Google.Protobuf.dll' to 'build/Plugins/Protobuf/Google.Protobuf.dll'...
DEBUG (build.py): Changing the mode of 'build/Plugins/Protobuf/Google.Protobuf.dll'...
DEBUG (build.py): Copying '.nuget/System.Runtime.CompilerServices.Unsafe.4.5.2/lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll' to 'build/Plugins/Protobuf/System.Runtime.CompilerServices.Unsafe.dll'...
DEBUG (build.py): Changing the mode of 'build/Plugins/Protobuf/System.Runtime.CompilerServices.Unsafe.dll'...
DEBUG (build.py): Copying '.nuget/System.Memory.4.5.3/lib/netstandard2.0/System.Memory.dll' to 'build/Plugins/Protobuf/System.Memory.dll'...
DEBUG (build.py): Changing the mode of 'build/Plugins/Protobuf/System.Memory.dll'...
INFO (build.py): Downloaded protobuf dlls
INFO (build.py): Building resource files
DEBUG (build.py): Running `bazel build -c opt --verbose_failures //mediapipe_api:mediapipe_assets`
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/2f6de37d68a4c69e2ff9eec3cebbf1369e496940.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "73106859751c2bc314861adc136d5cbecee3f7ae7d05539dc8235efbf4efdcbe"
DEBUG: Repository rules_cc instantiated at:
  /Users/admin/Downloads/MediaPipeUnityPlugin-master-2/WORKSPACE:90:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Analyzed target //mediapipe_api:mediapipe_assets (11 packages loaded, 54 targets configured).
INFO: Found 1 target...
Target //mediapipe_api:mediapipe_assets up-to-date:
  bazel-bin/mediapipe_api/mediapipe_assets.zip
INFO: Elapsed time: 22.977s, Critical Path: 17.18s
INFO: 28 processes: 2 internal, 26 darwin-sandbox.
INFO: Build completed successfully, 28 total actions
DEBUG (build.py): Unarchiving 'bazel-bin/mediapipe_api/mediapipe_assets.zip' to 'build/Resources'...
DEBUG (build.py): Unarchiving 'bazel-bin/mediapipe_api/mediapipe_assets.zip' to 'Assets/StreamingAssets'...
INFO (build.py): Built resource files
INFO (build.py): Building native libraries for Desktop...
DEBUG (build.py): Running `bazel build -c opt --verbose_failures --define MEDIAPIPE_DISABLE_GPU=1 --@opencv//:switch=local //mediapipe_api:mediapipe_desktop`
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/2f6de37d68a4c69e2ff9eec3cebbf1369e496940.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Build option --define has changed, discarding analysis cache.
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "73106859751c2bc314861adc136d5cbecee3f7ae7d05539dc8235efbf4efdcbe"
DEBUG: Repository rules_cc instantiated at:
  /Users/admin/Downloads/MediaPipeUnityPlugin-master-2/WORKSPACE:90:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
WARNING: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/com_google_mediapipe/mediapipe/framework/BUILD:54:24: in cc_library rule @com_google_mediapipe//mediapipe/framework:calculator_cc_proto: target '@com_google_mediapipe//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/com_google_mediapipe/mediapipe/framework/tool/BUILD:184:24: in cc_library rule @com_google_mediapipe//mediapipe/framework/tool:field_data_cc_proto: target '@com_google_mediapipe//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/a0ec971de0dc82e0bf8784393cb8c4a56c171045.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found
INFO: Analyzed target //mediapipe_api:mediapipe_desktop (106 packages loaded, 7799 targets configured).
INFO: Found 1 target...
INFO: From Compiling src/raw_logging.cc [for host]:
external/com_github_glog_glog/src/raw_logging.cc:139:3: warning: 'syscall' is deprecated: first deprecated in macOS 10.12 - syscall(2) is unsupported; please switch to a supported interface. For SYS_kdebug_trace use kdebug_signpost(). [-Wdeprecated-declarations]
  safe_write(STDERR_FILENO, buffer, strlen(buffer));
  ^
external/com_github_glog_glog/src/raw_logging.cc:63:34: note: expanded from macro 'safe_write'
# define safe_write(fd, s, len)  syscall(SYS_write, fd, s, len)
                                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/unistd.h:742:6: note: 'syscall' has been explicitly marked deprecated here
int      syscall(int, ...);
         ^
1 warning generated.
INFO: From Compiling src/utilities.cc [for host]:
external/com_github_glog_glog/src/utilities.cc:251:17: warning: 'syscall' is deprecated: first deprecated in macOS 10.12 - syscall(2) is unsupported; please switch to a supported interface. For SYS_kdebug_trace use kdebug_signpost(). [-Wdeprecated-declarations]
    pid_t tid = syscall(__NR_gettid);
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/unistd.h:742:6: note: 'syscall' has been explicitly marked deprecated here
int      syscall(int, ...);
         ^
1 warning generated.
INFO: From Compiling mediapipe/framework/deps/ret_check.cc [for host]:
In file included from external/com_google_mediapipe/mediapipe/framework/deps/ret_check.cc:15:
In file included from external/com_google_mediapipe/mediapipe/framework/deps/ret_check.h:19:
external/com_google_mediapipe/mediapipe/framework/deps/status_builder.h:95:12: warning: 'Status' is deprecated: Use absl::Status directly [-Wdeprecated-declarations]
  operator Status() const&;
           ^
external/com_google_mediapipe/mediapipe/framework/deps/status.h:30:14: note: 'Status' has been explicitly marked deprecated here
using Status ABSL_DEPRECATED("Use absl::Status directly") = absl::Status;
             ^
external/com_google_absl/absl/base/attributes.h:648:49: note: expanded from macro 'ABSL_DEPRECATED'
#define ABSL_DEPRECATED(message) __attribute__((deprecated(message)))
                                                ^
In file included from external/com_google_mediapipe/mediapipe/framework/deps/ret_check.cc:15:
In file included from external/com_google_mediapipe/mediapipe/framework/deps/ret_check.h:19:
external/com_google_mediapipe/mediapipe/framework/deps/status_builder.h:96:12: warning: 'Status' is deprecated: Use absl::Status directly [-Wdeprecated-declarations]
  operator Status() &&;
           ^
external/com_google_mediapipe/mediapipe/framework/deps/status.h:30:14: note: 'Status' has been explicitly marked deprecated here
using Status ABSL_DEPRECATED("Use absl::Status directly") = absl::Status;
             ^
external/com_google_absl/absl/base/attributes.h:648:49: note: expanded from macro 'ABSL_DEPRECATED'
#define ABSL_DEPRECATED(message) __attribute__((deprecated(message)))
                                                ^
2 warnings generated.
INFO: From Compiling mediapipe/framework/tool/text_to_binary_graph.cc [for host]:
In file included from external/com_google_mediapipe/mediapipe/framework/tool/text_to_binary_graph.cc:27:
In file included from external/com_google_mediapipe/mediapipe/framework/port/ret_check.h:18:
In file included from external/com_google_mediapipe/mediapipe/framework/deps/ret_check.h:19:
external/com_google_mediapipe/mediapipe/framework/deps/status_builder.h:95:12: warning: 'Status' is deprecated: Use absl::Status directly [-Wdeprecated-declarations]
  operator Status() const&;
           ^
external/com_google_mediapipe/mediapipe/framework/deps/status.h:30:14: note: 'Status' has been explicitly marked deprecated here
using Status ABSL_DEPRECATED("Use absl::Status directly") = absl::Status;
             ^
external/com_google_absl/absl/base/attributes.h:648:49: note: expanded from macro 'ABSL_DEPRECATED'
#define ABSL_DEPRECATED(message) __attribute__((deprecated(message)))
                                                ^
In file included from external/com_google_mediapipe/mediapipe/framework/tool/text_to_binary_graph.cc:27:
In file included from external/com_google_mediapipe/mediapipe/framework/port/ret_check.h:18:
In file included from external/com_google_mediapipe/mediapipe/framework/deps/ret_check.h:19:
external/com_google_mediapipe/mediapipe/framework/deps/status_builder.h:96:12: warning: 'Status' is deprecated: Use absl::Status directly [-Wdeprecated-declarations]
  operator Status() &&;
           ^
external/com_google_mediapipe/mediapipe/framework/deps/status.h:30:14: note: 'Status' has been explicitly marked deprecated here
using Status ABSL_DEPRECATED("Use absl::Status directly") = absl::Status;
             ^
external/com_google_absl/absl/base/attributes.h:648:49: note: expanded from macro 'ABSL_DEPRECATED'
#define ABSL_DEPRECATED(message) __attribute__((deprecated(message)))
                                                ^
2 warnings generated.
INFO: From Compiling mediapipe/framework/deps/status_builder.cc [for host]:
In file included from external/com_google_mediapipe/mediapipe/framework/deps/status_builder.cc:15:
external/com_google_mediapipe/mediapipe/framework/deps/status_builder.h:95:12: warning: 'Status' is deprecated: Use absl::Status directly [-Wdeprecated-declarations]
  operator Status() const&;
           ^
external/com_google_mediapipe/mediapipe/framework/deps/status.h:30:14: note: 'Status' has been explicitly marked deprecated here
using Status ABSL_DEPRECATED("Use absl::Status directly") = absl::Status;
             ^
external/com_google_absl/absl/base/attributes.h:648:49: note: expanded from macro 'ABSL_DEPRECATED'
#define ABSL_DEPRECATED(message) __attribute__((deprecated(message)))
                                                ^
In file included from external/com_google_mediapipe/mediapipe/framework/deps/status_builder.cc:15:
external/com_google_mediapipe/mediapipe/framework/deps/status_builder.h:96:12: warning: 'Status' is deprecated: Use absl::Status directly [-Wdeprecated-declarations]
  operator Status() &&;
           ^
external/com_google_mediapipe/mediapipe/framework/deps/status.h:30:14: note: 'Status' has been explicitly marked deprecated here
using Status ABSL_DEPRECATED("Use absl::Status directly") = absl::Status;
             ^
external/com_google_absl/absl/base/attributes.h:648:49: note: expanded from macro 'ABSL_DEPRECATED'
#define ABSL_DEPRECATED(message) __attribute__((deprecated(message)))
                                                ^
external/com_google_mediapipe/mediapipe/framework/deps/status_builder.cc:72:25: warning: 'Status' is deprecated: Use absl::Status directly [-Wdeprecated-declarations]
StatusBuilder::operator Status() const& {
                        ^
external/com_google_mediapipe/mediapipe/framework/deps/status.h:30:14: note: 'Status' has been explicitly marked deprecated here
using Status ABSL_DEPRECATED("Use absl::Status directly") = absl::Status;
             ^
external/com_google_absl/absl/base/attributes.h:648:49: note: expanded from macro 'ABSL_DEPRECATED'
#define ABSL_DEPRECATED(message) __attribute__((deprecated(message)))
                                                ^
external/com_google_mediapipe/mediapipe/framework/deps/status_builder.cc:79:25: warning: 'Status' is deprecated: Use absl::Status directly [-Wdeprecated-declarations]
StatusBuilder::operator Status() && {
                        ^
external/com_google_mediapipe/mediapipe/framework/deps/status.h:30:14: note: 'Status' has been explicitly marked deprecated here
using Status ABSL_DEPRECATED("Use absl::Status directly") = absl::Status;
             ^
external/com_google_absl/absl/base/attributes.h:648:49: note: expanded from macro 'ABSL_DEPRECATED'
#define ABSL_DEPRECATED(message) __attribute__((deprecated(message)))
                                                ^
external/com_google_mediapipe/mediapipe/framework/deps/status_builder.cc:100:10: warning: 'Status' is deprecated: Use absl::Status directly [-Wdeprecated-declarations]
  return Status(status_.code(), message);
         ^
external/com_google_mediapipe/mediapipe/framework/deps/status.h:30:14: note: 'Status' has been explicitly marked deprecated here
using Status ABSL_DEPRECATED("Use absl::Status directly") = absl::Status;
             ^
external/com_google_absl/absl/base/attributes.h:648:49: note: expanded from macro 'ABSL_DEPRECATED'
#define ABSL_DEPRECATED(message) __attribute__((deprecated(message)))
                                                ^
5 warnings generated.
Target //mediapipe_api:mediapipe_desktop up-to-date:
  bazel-bin/mediapipe_api/mediapipe_desktop.zip
INFO: Elapsed time: 5830.982s, Critical Path: 2365.50s
INFO: 3719 processes: 1137 internal, 2582 darwin-sandbox.
INFO: Build completed successfully, 3719 total actions
DEBUG (build.py): Unarchiving 'bazel-bin/mediapipe_api/mediapipe_desktop.zip' to 'build/Plugins'...
INFO (build.py): Built native libraries for Desktop
INFO (build.py): Building native libraries for Android...
DEBUG (build.py): Running `bazel build -c opt --verbose_failures --config=android_arm64 --java_runtime_version=remotejdk_11 //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android`
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/2f6de37d68a4c69e2ff9eec3cebbf1369e496940.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /private/var/tmp/_bazel_admin/38dff6c5b36768738c2afb113c06f5d6/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Build options --cpu, --crosstool_top, --define, and 4 more have changed, discarding analysis cache.
ERROR: /Users/admin/Downloads/MediaPipeUnityPlugin-master-2/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:10:14: While resolving toolchains for target //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
ERROR: Analysis of target '//mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android' failed; build aborted: 
INFO: Elapsed time: 4.590s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 215 targets co\
nfigured)
Traceback (most recent call last):
  File "/Users/admin/Downloads/MediaPipeUnityPlugin-master-2/build.py", line 469, in <module>
    Argument().command().run()
  File "/Users/admin/Downloads/MediaPipeUnityPlugin-master-2/build.py", line 150, in run
    self._run_command(self._build_android_commands())
  File "/Users/admin/Downloads/MediaPipeUnityPlugin-master-2/build.py", line 54, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel build -c opt --verbose_failures --config=android_arm64 --java_runtime_version=remotejdk_11 //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android' returned non-zero exit status 1.
```

**Comment by homuler** [comment]
> after 5 month I try again to build an iOS for my project

Pull the latest commit, please.
If the problem still occurs with it, please reopen it.

**Comment by ehsanwwe** [comment]
hello
i check the last commit its works without error 
but 
in the xcode build i have an error that say the bundle id must be unique
i think you forget to add ".mediapipeunity" at end of 
**mediapipe_api/objc/BUILD**
i remember  in the old version in the end of the **bundle_id**  we have an .MEDIUAPIPEUNITY or a text like it 
but in the new version it was deleted

do you think is this reason to i got this error ?
