### ISSUE TITLE
iOS build issue: Value cannot be null. (Parameter 'definition'))

### ISSUE THREAD

**Issue by TMW81** [homuler/MediaPipeUnityPlugin#783]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.9f1

### Your Host OS

Windows 11

### Target Platform

iOS

### Target Device

iPhone

### Build Command

instruction for Intel Mac

### Bug Description

When building for iOS in Unity (build is made on Windows 11), I got these exception and the build fails:
`System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'definition'))`

Build for Android is ok.
Log points to BuildProcessor `( (at Assets/MediaPipeUnity/Editor/BuildProcessor.cs:9))`, so the question is: is it connected to MediaPipeUnity Plugin?

Could you please help me resolve this issue? Thank you in advance for your help.

### Steps to Reproduce the Bug

Build in Unity 2021.3.9f on Windows 11, but targetting iOS.

### Log

```
'Exception: Unity.IL2CPP.Building.BuilderFailedException: Build failed with 0 successful nodes and 1 failed ones
Annotation: IL2CPP_CodeGen C:/Projects/!buildIosAWStries/Library/Il2cppBuildCache/iOS/buildstate/artifacts/il2cpp_conv_0m0l.traceevents
Cmdline: "C:\Program Files\Unity\Hub\Editor\2021.3.9f1\Editor\Data\il2cpp\build\deploy\il2cpp.exe" --convert-to-cpp --directory="C:/Projects/!buildIosAWStries/Temp/StagingArea/Data/Managed" --data-folder="C:\Projects\!buildIosAWStries\Library\Il2cppBuildCache\iOS\il2cppOutput\Data" --generatedcppdir="C:/Projects/!buildIosAWStries/Library/Il2cppBuildCache/iOS/il2cppOutput" --symbols-folder="C:\Projects\!buildIosAWStries\Library\Il2cppBuildCache\iOS\il2cppOutput\Symbols" --additional-cpp="C:/Projects/!buildIosAWStries/Library/Il2cppBuildCache/iOS/additionalCppFiles/UnityClassRegistration.cpp" --additional-cpp="C:/Projects/!buildIosAWStries/Library/Il2cppBuildCache/iOS/additionalCppFiles/UnityICallRegistration.cpp" --emit-null-checks --enable-array-bounds-check --code-generation-option=EnableInlining --stats-output-dir="C:/Projects/!buildIosAWStries/Library/Il2cppBuildCache/iOS/il2cppStats" --dotnetprofile=unityaot-macos --cachedirectory="C:/Projects/!buildIosAWStries/Library/Il2cppBuildCache/iOS" --profiler-report --profiler-output-file="C:/Projects/!buildIosAWStries/Library/Il2cppBuildCache/iOS/buildstate/artifacts/il2cpp_conv_0m0l.traceevents"
ExitCode: -1
Stdout: 
Error: IL2CPP error (no further information about what managed code was being converted is available)
System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'definition'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'definition')
   at Unity.IL2CPP.DataModel.TypeContext.GetDef(MethodDefinition definition)
   at Unity.IL2CPP.DataModel.BuildLogic.MethodReferenceResolver.ResolveMethodReference(TypeContext context, UnderConstructionMethodReferenceRepository repository, CecilSourcedAssemblyData assemblyData, MethodReference methodReference, Dictionary`2 mapping)
   at Unity.IL2CPP.DataModel.BuildLogic.MethodReferenceResolver.ResolveAssemblyMethodReferences(TypeContext context, UnderConstructionMethodReferenceRepository repository, CecilSourcedAssemblyData assemblyDef, ReadOnlyHashSet`1 methodReferences)
   at Unity.IL2CPP.DataModel.BuildLogic.DataModelBuilder.<>c__DisplayClass15_0.<ResolveReferences>b__0(CecilSourcedAssemblyData data)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Unity.IL2CPP.DataModel.BuildLogic.Utils.ParallelHelpers.ForEach[TSource](IEnumerable`1 source, Action`1 func, Boolean enableSerial)
   at Unity.IL2CPP.DataModel.BuildLogic.DataModelBuilder.Build()
   at Unity.IL2CPP.Contexts.Components.DataModelComponent.Load(LoadSettings loadSettings, Boolean ownsTypeContext, Boolean ownsBuilder, DataModelBuilder& builder)
   at Unity.IL2CPP.AssemblyConversion.Phases.InitializePhase.Run(AssemblyConversionContext context)
   at Unity.IL2CPP.AssemblyConversion.Classic.ClassicConverter.Run(AssemblyConversionContext context)
   at Unity.IL2CPP.AssemblyConversion.AssemblyConverter.ConvertAssemblies(AssemblyConversionInputData data, AssemblyConversionParameters parameters, AssemblyConversionInputDataForTopLevelAccess dataForTopLevel)

   at il2cpp.Program.DoRun(String[] args, RuntimePlatform platform, Il2CppCommandLineArguments il2CppCommandLineArguments, BuildingOptions buildingOptions, Boolean throwExceptions)
UnityEditorInternal.Runner.RunProgram (UnityEditor.Utils.Program p, System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser) (at <0d6ce211ebbc47e1a35a84c3672ff58f>:0)
UnityEditorInternal.Runner.RunNetCoreProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, System.Action`1[T] setupStartInfo) (at <0d6ce211ebbc47e1a35a84c3672ff58f>:0)
UnityEditorInternal.IL2CPPBuilder.RunIl2CppWithArguments (System.Collections.Generic.List`1[T] arguments, System.Action`1[T] setupStartInfo) (at <0d6ce211ebbc47e1a35a84c3672ff58f>:0)
UnityEditorInternal.IL2CPPBuilder.ConvertPlayerDlltoCpp (UnityEditor.Il2Cpp.Il2CppBuildPipelineData data) (at <0d6ce211ebbc47e1a35a84c3672ff58f>:0)
UnityEditorInternal.IL2CPPBuilder.Run () (at <0d6ce211ebbc47e1a35a84c3672ff58f>:0)
UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String tempFolder, System.String stagingAreaData, UnityEditorInternal.IIl2CppPlatformProvider platformProvider, System.Action`1[T] modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry) (at <0d6ce211ebbc47e1a35a84c3672ff58f>:0)
UnityEditor.iOS.PostProcessiPhonePlayer.CrossCompileManagedDlls (UnityEditor.iOS.PostProcessiPhonePlayer+BuildSettings bs, UnityEditor.iOS.PostProcessiPhonePlayer+ProjectPaths paths, UnityEditor.AssemblyReferenceChecker checker, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport buildReport) (at C:/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:932)
UnityEditor.iOS.PostProcessiPhonePlayer.PostProcess (UnityEditor.iOS.PostProcessiPhonePlayer+BuildSettings bs, UnityEditor.iOS.PostProcessiPhonePlayer+ProjectPaths paths, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport buildReport) (at C:/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:755)
UnityEditor.iOS.PostProcessiPhonePlayer.PostProcess (UnityEditor.iOS.PostProcessorSettings postProcessorSettings, UnityEditor.Modules.BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:695)
UnityEditor.iOS.iOSBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/ExtensionModule.cs:45)
Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown.
UnityEditor.iOS.iOSBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/ExtensionModule.cs:49)
UnityEditor.Modules.DefaultBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <0d6ce211ebbc47e1a35a84c3672ff58f>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.Int32 subtarget, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <0d6ce211ebbc47e1a35a84c3672ff58f>:0)
UnityEditor.DefaultBuildMethods:BuildPlayer(BuildPlayerOptions)
<>c:<.cctor>b__0_0(BuildPlayerOptions) (at Assets/MediaPipeUnity/Editor/BuildProcessor.cs:9)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)
'
```

**Comment by TMW81** [comment]
Solved - changed Magaed Stripping Level to Low (minimal causes issue).
This bug is probably Unity Editor bug, not connected with this wonderful Plugin :)
Sorry for taking time :)

**Comment by TMW81** [comment]
Solved - changed Managed Stripping Level to Low (minimal causes issue).
This bug is probably Unity Editor bug, not connected with this wonderful Plugin :)
Sorry for taking time :)
