### ISSUE TITLE
Error when building on Windows desktop - Python is not executable

### ISSUE THREAD

**Issue by Julia-Melgare** [homuler/MediaPipeUnityPlugin#786]
### Plugin Version or Commit ID

391d7d9

### Unity Version

2021.3.3f1

### Your Host OS

Windows 10 Home

### Target Platform

UnityEditor, Windows Standalone

### [Windows Only] Visual Studio C++ and Windows SDK Version

Visual Studio C++: 16.11.21
Windows SDK: 10.0.19041.685

### Command Sequences

`set BAZEL_VS=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTool`
`set BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC`
`set BAZEL_VC_FULL_VERSION=16.11.21`
`set BAZEL_WINSDK_FULL_VERSION=10.0.19041.685`
`python build.py build --desktop cpu --opencv=cmake -v`

### Log

```
C:\MediaPipeUnityPlugin> python build.py build --desktop cpu --opencv=cmake -vv
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//jujum//AppData//Local//Programs//Python//Python311//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures //mediapipe_api:mediapipe_proto_srcs`
Starting local Bazel server and connecting to it...
DEBUG: C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Repository local_execution_config_python instantiated at:
  C:/mediapipeunityplugin/WORKSPACE:433:14: in <toplevel>
  C:/_bzl/kwr2wusf/external/org_tensorflow/tensorflow/workspace2.bzl:868:19: in workspace
  C:/_bzl/kwr2wusf/external/org_tensorflow/tensorflow/workspace2.bzl:91:27: in _tf_toolchains
  C:/_bzl/kwr2wusf/external/tf_toolchains/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  C:/_bzl/kwr2wusf/external/tf_toolchains/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/py/python_configure.bzl:279:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C://Users//jujum//AppData//Local//Programs//Python//Python311//python.exe' is not executable. Is it the python binary?
ERROR: C:/mediapipeunityplugin/WORKSPACE:433:14: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):
        File "C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C://Users//jujum//AppData//Local//Programs//Python//Python311//python.exe' is not executable. Is it the python binary?
INFO: Repository rules_cc instantiated at:
  C:/mediapipeunityplugin/WORKSPACE:90:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/kwr2wusf/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: Configuration Error: --define PYTHON_BIN_PATH='C://Users//jujum//AppData//Local//Programs//Python//Python311//python.exe' is not executable. Is it the python binary?
INFO: Elapsed time: 2191.127s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (65 packages loaded, 23 targets configured)
    currently loading: @com_google_mediapipe//mediapipe/graphs/object_detection_3d/calculators ... (20 packages)
    Fetching @com_google_protobuf; fetching
    Fetching C:/_bzl/kwr2wusf/external/com_google_protobuf; Extracting C:/_bzl/kwr2wusf/external/com_google_protobuf/temp11091037392828369330/v3.19.1.tar.gz
    Fetching @local_config_cuda; fetching
Traceback (most recent call last):
  File "C:\MediaPipeUnityPlugin\build.py", line 469, in <module>
    Argument().command().run()
  File "C:\MediaPipeUnityPlugin\build.py", line 112, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\MediaPipeUnityPlugin\build.py", line 54, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jujum\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 569, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//jujum//AppData//Local//Programs//Python//Python311//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 1.
```

### Additional Context

The value of `PYTHON_BIN_PATH` is correct, so I don't understand why I'm getting this error. 
Whenever I run python using this exact path, it works:

```
C:\MediaPipeUnityPlugin>C://Users//jujum//AppData//Local//Programs//Python//Python311//python.exe
Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by homuler** [comment]
Maybe the same issue as #746 .
Which `bash` is used when you run `bash`? (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/746#issuecomment-1264594018)
