### ISSUE TITLE
Build Failed  Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed;

### ISSUE THREAD

**Issue by BilalatNarsun** [homuler/MediaPipeUnityPlugin#796]
### Description

When I run python build.py build --desktop cpu -v
Facing these errors but It was working before. I don't know what happened now.  here is the error from stack trace
**ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: Repository command failed
INFO: Could not find files for the given pattern(s).**

I did all the installation steps and also I am not using Docker. Also I have gone through all the previous issues but couldn't resolve it. [191](https://github.com/homuler/MediaPipeUnityPlugin/issues/191) [230](https://github.com/homuler/MediaPipeUnityPlugin/issues/230)

More Information.
INFO: Repository local_execution_config_python instantiated at:
  C:/users/fatima/desktop/bilalwork/mediapipeunityplugin-master/WORKSPACE:433:14: in <toplevel>
  C:/_bzl/uvkb24d2/external/org_tensorflow/tensorflow/workspace2.bzl:868:19: in workspace
  C:/_bzl/uvkb24d2/external/org_tensorflow/tensorflow/workspace2.bzl:91:27: in _tf_toolchains
  C:/_bzl/uvkb24d2/external/tf_toolchains/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  C:/_bzl/uvkb24d2/external/tf_toolchains/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  C:/_bzl/uvkb24d2/external/org_tensorflow/third_party/py/python_configure.bzl:279:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/_bzl/uvkb24d2/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/_bzl/uvkb24d2/external/org_tensorflow/third_party/py/python_configure.bzl", line 143, column 52, in _check_python_bin
                result = raw_exec(repository_ctx, [get_bash_bin(repository_ctx), "-c", cmd])
        File "C:/_bzl/uvkb24d2/external/org_tensorflow/third_party/remote_config/common.bzl", line 88, column 26, in get_bash_bin
                bash_bin_path = which(repository_ctx, "bash")
        File "C:/_bzl/uvkb24d2/external/org_tensorflow/third_party/remote_config/common.bzl", line 27, column 22, in which
                out = execute(
        File "C:/_bzl/uvkb24d2/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
INFO: Could not find files for the given pattern(s).
ERROR: C:/users/fatima/desktop/bilalwork/mediapipeunityplugin-master/WORKSPACE:433:14: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):
        File "C:/_bzl/uvkb24d2/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/_bzl/uvkb24d2/external/org_tensorflow/third_party/py/python_configure.bzl", line 143, column 52, in _check_python_bin
                result = raw_exec(repository_ctx, [get_bash_bin(repository_ctx), "-c", cmd])
        File "C:/_bzl/uvkb24d2/external/org_tensorflow/third_party/remote_config/common.bzl", line 88, column 26, in get_bash_bin
                bash_bin_path = which(repository_ctx, "bash")
        File "C:/_bzl/uvkb24d2/external/org_tensorflow/third_party/remote_config/common.bzl", line 27, column 22, in which
                out = execute(
        File "C:/_bzl/uvkb24d2/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
INFO: Could not find files for the given pattern(s).
INFO: Repository rules_cc instantiated at:
  C:/users/fatima/desktop/bilalwork/mediapipeunityplugin-master/WORKSPACE:90:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/uvkb24d2/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: Repository command failed
INFO: Could not find files for the given pattern(s).
INFO: Elapsed time: 1.371s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (3 packages loaded, 0 targets configured)

**Comment by homuler** [comment]
Please use [the Build/Install issue form](https://github.com/homuler/MediaPipeUnityPlugin/issues/new?assignees=&labels=type%3Abuild%2Finstall&template=build-install-issue.yml).
Note that you don't need to build libraries on your local machine anymore (you can download the pre-built package or use GitHub Actions workflow).


> bash_bin_path = which(repository_ctx, "bash")

I'm not sure, but maybe `bash.exe` is missing (`where bash.exe` have failed).
