### ISSUE TITLE
(already checked #350)'@local_config_cc//:toolchain' does not contain a toolchain for cpu 'ios_arm64'

### ISSUE THREAD

**Issue by efan006** [homuler/MediaPipeUnityPlugin#894]
### Plugin Version or Commit ID

v0.11.0

### Unity Version

2021.3.0

### Your Host OS

macOS 13.3.1(Intel chip)

### Target Platform

iOS

### [iOS Only] XCode Version

Version 14.3 (14E222b)

### Command Sequences

% xcode-select -p
/Applications/Xcode.app/Contents/Developer
% python3 build.py clean
INFO: Starting clean.
% python3 build.py build --ios arm64 -vvv

### Log

ERROR: /private/var/tmp/_bazel_efan/8cecf9a79ca1b25f9c81c60b1a608804/external/local_config_cc/BUILD:48:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'ios_arm64'
ERROR: /private/var/tmp/_bazel_efan/8cecf9a79ca1b25f9c81c60b1a608804/external/local_config_cc/BUILD:48:19: Analysis of target '@local_config_cc//:toolchain' failed
ERROR: Analysis of target '//mediapipe_api/objc:MediaPipeUnity' failed; build aborted: 
INFO: Elapsed time: 1.500s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (18 packages loaded, 833 targets c\
onfigured)
Traceback (most recent call last):
  File "/Users/efan/AIWorks/MediaPipeUnityPlugin/build.py", line 471, in <module>
    Argument().command().run()
  File "/Users/efan/AIWorks/MediaPipeUnityPlugin/build.py", line 161, in run
    self._run_command(self._build_ios_commands())
  File "/Users/efan/AIWorks/MediaPipeUnityPlugin/build.py", line 56, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "/Users/efan/anaconda3/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel build -c opt --verbose_failures --sandbox_debug --config=ios_arm64 --copt=-fembed-bitcode --apple_bitcode=embedded //mediapipe_api/objc:MediaPipeUnity' returned non-zero exit status 1.

### Additional Context

I've already checked the issue: https://github.com/homuler/MediaPipeUnityPlugin/issues/350
It seems the error occurred again in Xcode 14.3?

I looked up the place /private/var/tmp/_bazel_efan/8cecf9a79ca1b25f9c81c60b1a608804/external/local_config_cc/BUILD:48:19:
```
# This is the entry point for --crosstool_top.  Toolchains are found
# by lopping off the name of --crosstool_top and searching for
# the "${CPU}" entry in the toolchains attribute.
cc_toolchain_suite(
    name = "toolchain",
    toolchains = {
        "darwin|clang": ":cc-compiler-darwin",
        "darwin": ":cc-compiler-darwin",
        "armeabi-v7a|compiler": ":cc-compiler-armeabi-v7a",
        "armeabi-v7a": ":cc-compiler-armeabi-v7a",
    },
)
```
It does not contain 'ios_arm64'
How could I add 'ios_arm64' in toolchain?

**Comment by efan006** [comment]
> I'm a little confused, if not on my local machine, where should I build?

**Comment by homuler** [comment]
https://github.com/homuler/MediaPipeUnityPlugin#hammer_and_wrench-installation
> You can download them from [the release page](https://github.com/homuler/MediaPipeUnityPlugin/releases) instead.
> You can also make use of [the Package Workflow](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/.github/workflows/package.yml) on GitHub Actions after forking this repository.

So you don't need to build it by yourself in most cases.
If you want to build with custom options, you can still use GitHub Actions.

**Comment by efan006** [comment]
sorry I misunderstanded your meaning. I made some modifications to the MediaPipe calculator (such as enabling the hand world landmarks in holistic solution), so I need to build a new one

**Comment by homuler** [comment]
Then please try the Package Workflow on GitHub Actions.
