### ISSUE TITLE
Android build fail with Mac Intel

### ISSUE THREAD

**Issue by cadenKST** [homuler/MediaPipeUnityPlugin#950]
### Plugin Version or Commit ID

v0.12.0

### Unity Version

2021.1.3.18f1

### Your Host OS

MacOs 12.6.3 (21G419) Intel

### Target Platform

Android, iOS

### [Android Only] Android Build Tools and NDK Version

SDK:30.0.3
NDK:21.4.7

### [iOS Only] XCode Version

Xcode 14.2

### Command Sequences

python build.py build --android arm64 --android_ndk_api_level 21 -vv

### Log

```txt
(base) caden.ks.tang@CadenTang-MBP-635-20 MediaPipeUnityPlugin % python build.py build --android arm64 --android_ndk_api_level 21 -vv
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel build -c opt --action_env ANDROID_NDK_API_LEVEL="21" --verbose_failures //mediapipe_api:mediapipe_proto_srcs`
INFO: Build options --copt, --cpu, --crosstool_top, and 4 more have changed, discarding analysis cache.
INFO: Analyzed target //mediapipe_api:mediapipe_proto_srcs (0 packages loaded, 1209 targets configured).
INFO: Found 1 target...
Target //mediapipe_api:mediapipe_proto_srcs up-to-date:
  bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip
INFO: Elapsed time: 0.860s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
DEBUG (build.py): Unarchiving 'bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip' to 'build/Runtime/Scripts/Protobuf'...
INFO (build.py): Built protobuf sources
INFO (build.py): Downloading dlls...
DEBUG (build.py): Running `nuget install -o .nuget -Source https://api.nuget.org/v3/index.json`
Feeds used:
  /Users/caden.ks.tang/.nuget/packages/
  https://api.nuget.org/v3/index.json

All packages listed in /Users/caden.ks.tang/Documents/project/mediapipeAndriod/MediaPipeUnityPlugin/packages.config are already installed.
DEBUG (build.py): Copying '.nuget/System.Buffers.4.4.0/lib/netstandard2.0/System.Buffers.dll' to 'build/Runtime/Plugins/Protobuf/System.Buffers.dll'...
DEBUG (build.py): Changing the mode of 'build/Runtime/Plugins/Protobuf/System.Buffers.dll'...
DEBUG (build.py): Copying '.nuget/Google.Protobuf.3.20.0/lib/netstandard2.0/Google.Protobuf.dll' to 'build/Runtime/Plugins/Protobuf/Google.Protobuf.dll'...
DEBUG (build.py): Changing the mode of 'build/Runtime/Plugins/Protobuf/Google.Protobuf.dll'...
DEBUG (build.py): Copying '.nuget/System.Runtime.CompilerServices.Unsafe.4.5.2/lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll' to 'build/Runtime/Plugins/Protobuf/System.Runtime.CompilerServices.Unsafe.dll'...
DEBUG (build.py): Changing the mode of 'build/Runtime/Plugins/Protobuf/System.Runtime.CompilerServices.Unsafe.dll'...
DEBUG (build.py): Copying '.nuget/System.Memory.4.5.3/lib/netstandard2.0/System.Memory.dll' to 'build/Runtime/Plugins/Protobuf/System.Memory.dll'...
DEBUG (build.py): Changing the mode of 'build/Runtime/Plugins/Protobuf/System.Memory.dll'...
INFO (build.py): Downloaded protobuf dlls
INFO (build.py): Building resource files
DEBUG (build.py): Running `bazel build -c opt --action_env ANDROID_NDK_API_LEVEL="21" --verbose_failures //mediapipe_api:mediapipe_assets`
INFO: Analyzed target //mediapipe_api:mediapipe_assets (0 packages loaded, 97 targets configured).
INFO: Found 1 target...
Target //mediapipe_api:mediapipe_assets up-to-date:
  bazel-bin/mediapipe_api/mediapipe_assets.zip
INFO: Elapsed time: 0.425s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
DEBUG (build.py): Unarchiving 'bazel-bin/mediapipe_api/mediapipe_assets.zip' to 'build/PackageResources/MediaPipe'...
DEBUG (build.py): Unarchiving 'bazel-bin/mediapipe_api/mediapipe_assets.zip' to 'Assets/StreamingAssets'...
INFO (build.py): Built resource files
INFO (build.py): Building native libraries for Android...
DEBUG (build.py): Running `bazel build -c opt --action_env ANDROID_NDK_API_LEVEL="21" --verbose_failures --config=android_arm64 --java_runtime_version=remotejdk_11 //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android`
INFO: Build options --copt, --cpu, --crosstool_top, and 4 more have changed, discarding analysis cache.
WARNING: /private/var/tmp/_bazel_caden.ks.tang/6e9e1652c6d6a674ea7e3702108870b4/external/com_google_mediapipe/mediapipe/framework/tool/BUILD:197:24: in cc_library rule @com_google_mediapipe//mediapipe/framework/tool:field_data_cc_proto: target '@com_google_mediapipe//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: /private/var/tmp/_bazel_caden.ks.tang/6e9e1652c6d6a674ea7e3702108870b4/external/com_google_mediapipe/mediapipe/framework/BUILD:56:24: in cc_library rule @com_google_mediapipe//mediapipe/framework:calculator_cc_proto: target '@com_google_mediapipe//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Analyzed target //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android (0 packages loaded, 19525 targets configured).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_caden.ks.tang/6e9e1652c6d6a674ea7e3702108870b4/external/com_google_mediapipe/mediapipe/modules/pose_landmark/BUILD:174:26: Linking external/com_google_mediapipe/mediapipe/modules/pose_landmark/pose_detection_to_roi_graph_text_to_binary_graph [for tool] failed: (Exit 1): cc_wrapper.sh failed: error executing command (from target @com_google_mediapipe//mediapipe/modules/pose_landmark:pose_detection_to_roi_graph_text_to_binary_graph) 
  (cd /private/var/tmp/_bazel_caden.ks.tang/6e9e1652c6d6a674ea7e3702108870b4/sandbox/darwin-sandbox/129/execroot/mediapipe_api && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=13.1 \
    PATH=/Users/caden.ks.tang/Library/Caches/bazelisk/downloads/bazelbuild/bazel-6.1.1-darwin-x86_64/bin:/Users/caden.ks.tang/homebrew/opt/opencv@3/bin:/Users/caden.ks.tang/anaconda3/bin:/Users/caden.ks.tang/anaconda3/condabin:/Users/caden.ks.tang/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin \
    XCODE_VERSION_OVERRIDE=14.2.0.14C18 \
    ZERO_AR_DATE=1 \
  external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-opt-exec-50AE0418/bin/external/com_google_mediapipe/mediapipe/modules/pose_landmark/pose_detection_to_roi_graph_text_to_binary_graph-2.params)
# Configuration: 4732cb205a3fd134e4cdf5ff94e579ff5a4809821cc49d216d1bf907efc170e7
# Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
stderr (/private/var/tmp/_bazel_caden.ks.tang/6e9e1652c6d6a674ea7e3702108870b4/execroot/mediapipe_api/bazel-out/_tmp/actions/stderr-12) 1461976 exceeds maximum size of --experimental_ui_max_stdouterr_bytes=1048576 bytes; skipping
ERROR: /private/var/tmp/_bazel_caden.ks.tang/6e9e1652c6d6a674ea7e3702108870b4/external/com_google_mediapipe/mediapipe/modules/holistic_landmark/BUILD:71:26: Linking external/com_google_mediapipe/mediapipe/modules/holistic_landmark/face_detection_front_detections_to_roi_graph_text_to_binary_graph [for tool] failed: (Exit 1): cc_wrapper.sh failed: error executing command (from target @com_google_mediapipe//mediapipe/modules/holistic_landmark:face_detection_front_detections_to_roi_graph_text_to_binary_graph) 
  (cd /private/var/tmp/_bazel_caden.ks.tang/6e9e1652c6d6a674ea7e3702108870b4/sandbox/darwin-sandbox/132/execroot/mediapipe_api && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=13.1 \
    PATH=/Users/caden.ks.tang/Library/Caches/bazelisk/downloads/bazelbuild/bazel-6.1.1-darwin-x86_64/bin:/Users/caden.ks.tang/homebrew/opt/opencv@3/bin:/Users/caden.ks.tang/anaconda3/bin:/Users/caden.ks.tang/anaconda3/condabin:/Users/caden.ks.tang/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin \
    XCODE_VERSION_OVERRIDE=14.2.0.14C18 \
    ZERO_AR_DATE=1 \
  external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-opt-exec-50AE0418/bin/external/com_google_mediapipe/mediapipe/modules/holistic_landmark/face_detection_front_detections_to_roi_graph_text_to_binary_graph-2.params)
# Configuration: 4732cb205a3fd134e4cdf5ff94e579ff5a4809821cc49d216d1bf907efc170e7
# Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
stderr (/private/var/tmp/_bazel_caden.ks.tang/6e9e1652c6d6a674ea7e3702108870b4/execroot/mediapipe_api/bazel-out/_tmp/actions/stderr-16) 1461976 exceeds maximum size of --experimental_ui_max_stdouterr_bytes=1048576 bytes; skipping
ERROR: /private/var/tmp/_bazel_caden.ks.tang/6e9e1652c6d6a674ea7e3702108870b4/external/com_google_mediapipe/mediapipe/modules/face_landmark/BUILD:143:26: Linking external/com_google_mediapipe/mediapipe/modules/face_landmark/face_detection_front_detection_to_roi_graph_text_to_binary_graph [for tool] failed: (Exit 1): cc_wrapper.sh failed: error executing command (from target @com_google_mediapipe//mediapipe/modules/face_landmark:face_detection_front_detection_to_roi_graph_text_to_binary_graph) 
  (cd /private/var/tmp/_bazel_caden.ks.tang/6e9e1652c6d6a674ea7e3702108870b4/sandbox/darwin-sandbox/143/execroot/mediapipe_api && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=13.1 \
    PATH=/Users/caden.ks.tang/Library/Caches/bazelisk/downloads/bazelbuild/bazel-6.1.1-darwin-x86_64/bin:/Users/caden.ks.tang/homebrew/opt/opencv@3/bin:/Users/caden.ks.tang/anaconda3/bin:/Users/caden.ks.tang/anaconda3/condabin:/Users/caden.ks.tang/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin \
    XCODE_VERSION_OVERRIDE=14.2.0.14C18 \
    ZERO_AR_DATE=1 \
  external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-opt-exec-50AE0418/bin/external/com_google_mediapipe/mediapipe/modules/face_landmark/face_detection_front_detection_to_roi_graph_text_to_binary_graph-2.params)
# Configuration: 4732cb205a3fd134e4cdf5ff94e579ff5a4809821cc49d216d1bf907efc170e7
# Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
stderr (/private/var/tmp/_bazel_caden.ks.tang/6e9e1652c6d6a674ea7e3702108870b4/execroot/mediapipe_api/bazel-out/_tmp/actions/stderr-37) 1461976 exceeds maximum size of --experimental_ui_max_stdouterr_bytes=1048576 bytes; skipping
Target //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android failed to build
INFO: Elapsed time: 8.713s, Critical Path: 5.85s
INFO: 129 processes: 129 internal.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "/Users/caden.ks.tang/Documents/project/mediapipeAndriod/MediaPipeUnityPlugin/build.py", line 470, in <module>
    Argument().command().run()
  File "/Users/caden.ks.tang/Documents/project/mediapipeAndriod/MediaPipeUnityPlugin/build.py", line 152, in run
    self._run_command(self._build_android_commands())
  File "/Users/caden.ks.tang/Documents/project/mediapipeAndriod/MediaPipeUnityPlugin/build.py", line 56, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "/Users/caden.ks.tang/anaconda3/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel build -c opt --action_env ANDROID_NDK_API_LEVEL="21" --verbose_failures --config=android_arm64 --java_runtime_version=remotejdk_11 //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android' returned non-zero exit status 1.
(base) caden.ks.tang@CadenTang-MBP-635-20 MediaPipeUnityPlugin % 
```

### Additional Context
```txt
(base) caden.ks.tang@CadenTang-MBP-635-20 ~ % env
__CFBundleIdentifier=com.apple.Terminal
TMPDIR=/var/folders/91/9dvjl2x509141zzyn23y05b1455qf6/T/
XPC_FLAGS=0x0
TERM=xterm-256color
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.5cHrBXil8s/Listeners
XPC_SERVICE_NAME=0
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=445
TERM_SESSION_ID=7B2F99C4-534F-42FC-BC0D-CD6A9E0E6826
SHELL=/bin/zsh
HOME=/Users/caden.ks.tang
LOGNAME=caden.ks.tang
USER=caden.ks.tang
PATH=/Users/caden.ks.tang/homebrew/opt/opencv@3/bin:/Users/caden.ks.tang/anaconda3/bin:/Users/caden.ks.tang/anaconda3/condabin:/Users/caden.ks.tang/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
SHLVL=1
PWD=/Users/caden.ks.tang
OLDPWD=/Users/caden.ks.tang
ANDROID_HOME=/Users/caden.ks.tang/Library/Android/sdk
ANDROID_NDK_HOME=/Users/caden.ks.tang/Library/Android/sdk/ndk/21.4.7075529
LDFLAGS=-L/Users/caden.ks.tang/homebrew/opt/opencv@3/lib
CPPFLAGS=-I/Users/caden.ks.tang/homebrew/opt/opencv@3/include
PKG_CONFIG_PATH=/Users/caden.ks.tang/homebrew/opt/opencv@3/lib/pkgconfig
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home
CONDA_EXE=/Users/caden.ks.tang/anaconda3/bin/conda
_CE_M=
_CE_CONDA=
CONDA_PYTHON_EXE=/Users/caden.ks.tang/anaconda3/bin/python
CONDA_SHLVL=1
CONDA_PREFIX=/Users/caden.ks.tang/anaconda3
CONDA_DEFAULT_ENV=base
CONDA_PROMPT_MODIFIER=(base) 
LC_CTYPE=UTF-8
_=/usr/bin/env
(base) caden.ks.tang@CadenTang-MBP-635-20 ~ % 
```

**Comment by cadenKST** [comment]
(base) caden.ks.tang@CadenTang-MBP-635-20 MediaPipeUnityPlugin % bazel build -c opt --action_env ANDROID_NDK_API_LEVEL="21" --verbose_failures --config=android_arm64 --java_runtime_version=remotejdk_11 //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android
WARNING: /private/var/tmp/_bazel_caden.ks.tang/6e9e1652c6d6a674ea7e3702108870b4/external/com_google_mediapipe/mediapipe/framework/BUILD:56:24: in cc_library rule @com_google_mediapipe//mediapipe/framework:calculator_cc_proto: target '@com_google_mediapipe//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: /private/var/tmp/_bazel_caden.ks.tang/6e9e1652c6d6a674ea7e3702108870b4/external/com_google_mediapipe/mediapipe/framework/tool/BUILD:197:24: in cc_library rule @com_google_mediapipe//mediapipe/framework/tool:field_data_cc_proto: target '@com_google_mediapipe//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Analyzed target //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_caden.ks.tang/6e9e1652c6d6a674ea7e3702108870b4/external/com_google_mediapipe/mediapipe/modules/face_landmark/BUILD:176:26: Linking external/com_google_mediapipe/mediapipe/modules/face_landmark/tensors_to_face_landmarks_graph_text_to_binary_graph [for tool] failed: (Exit 1): cc_wrapper.sh failed: error executing command (from target @com_google_mediapipe//mediapipe/modules/face_landmark:tensors_to_face_landmarks_graph_text_to_binary_graph) 
  (cd /private/var/tmp/_bazel_caden.ks.tang/6e9e1652c6d6a674ea7e3702108870b4/sandbox/darwin-sandbox/2111/execroot/mediapipe_api && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=13.1 \
    PATH=/Users/caden.ks.tang/Library/Caches/bazelisk/downloads/bazelbuild/bazel-6.1.1-darwin-x86_64/bin:/Users/caden.ks.tang/homebrew/opt/opencv@3/bin:/Users/caden.ks.tang/anaconda3/bin:/Users/caden.ks.tang/anaconda3/condabin:/Users/caden.ks.tang/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin \
    XCODE_VERSION_OVERRIDE=14.2.0.14C18 \
    ZERO_AR_DATE=1 \
  external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-opt-exec-50AE0418/bin/external/com_google_mediapipe/mediapipe/modules/face_landmark/tensors_to_face_landmarks_graph_text_to_binary_graph-2.params)
# Configuration: 4732cb205a3fd134e4cdf5ff94e579ff5a4809821cc49d216d1bf907efc170e7
# Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
stderr (/private/var/tmp/_bazel_caden.ks.tang/6e9e1652c6d6a674ea7e3702108870b4/execroot/mediapipe_api/bazel-out/_tmp/actions/stderr-15) 1461976 exceeds maximum size of --experimental_ui_max_stdouterr_bytes=1048576 bytes; skipping
Target //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android failed to build
INFO: Elapsed time: 1.647s, Critical Path: 1.34s
INFO: 129 processes: 129 internal.
FAILED: Build did NOT complete successfully

**Comment by homuler** [comment]
> 1461976 exceeds maximum size of --experimental_ui_max_stdouterr_bytes=1048576 bytes; 

Try running `python build.py build --bazel_build_opts="--experimental_ui_max_stdouterr_bytes=2000000" --android arm64 --android_ndk_api_level 21 -vv`.

By the way, when you'd like to build your own library, I strongly recommend you make use of GitHub Actions (cf. https://github.com/homuler/MediaPipeUnityPlugin#hammer_and_wrench-installation).

**Comment by cadenKST** [comment]
@homuler Thanks for the reply. After I run `python build.py build --bazel_build_opts="--experimental_ui_max_stdouterr_bytes=2000000" --android arm64 --android_ndk_api_level 21 -vv`, it pop up the error (the full error log is in the stdouterrLog.txt) : 

FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "/Users/caden.ks.tang/Documents/project/mediapipeAndriod/MediaPipeUnityPlugin/build.py", line 470, in <module>
    Argument().command().run()
  File "/Users/caden.ks.tang/Documents/project/mediapipeAndriod/MediaPipeUnityPlugin/build.py", line 152, in run
    self._run_command(self._build_android_commands())
  File "/Users/caden.ks.tang/Documents/project/mediapipeAndriod/MediaPipeUnityPlugin/build.py", line 56, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "/Users/caden.ks.tang/anaconda3/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel build -c opt --action_env ANDROID_NDK_API_LEVEL="21" --verbose_failures --experimental_ui_max_stdouterr_bytes=2000000 --config=android_arm64 --java_runtime_version=remotejdk_11 //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android' returned non-zero exit status 1.

[stdouterrLog.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/12010154/stdouterrLog.txt)

I also try `python build.py build --bazel_build_opts="--experimental_ui_max_stdouterr_bytes=5000000" --android arm64 --android_ndk_api_level 21 -vv`, it still show the same error.

**Comment by homuler** [comment]
It seems to me a similar issue to [this](https://github.com/google/mediapipe/issues/4296).
Please try using a platform other than macOS (e.g. [the build-package workflow](https://github.com/homuler/MediaPipeUnityPlugin/actions/workflows/build-package.yml)) or consider [applying a patch to Bazel](https://github.com/homuler/MediaPipeUnityPlugin/pull/924/commits/828786b4762ce7732f5d438b02641e561d5d8848).

**Comment by homuler** [comment]
By the way, note that you don't need to build libraries by yourself in most cases (if you don't need to customize the build).
