### ISSUE TITLE
Linker error building on Windows

### ISSUE THREAD

**Issue by cdiddy77** [homuler/MediaPipeUnityPlugin#963]
### Plugin Version or Commit ID

v0.12.0

### Unity Version

2021.3.18f1

### Your Host OS

Windows 11

### Target Platform

Windows Standalone

### [Windows Only] Visual Studio C++ and Windows SDK Version

VCToolsVersion=14.34.31933
VisualStudioVersion=17.0
WindowsSDKVersion=10.0.22000.0\

### Command Sequences

python build.py build --desktop cpu --opencv cmake -vv

### Log
```
ERROR: C:/users/charl/dev/getfilta/nplus1/packages/mpup/mediapipe_api/BUILD:217:10: Linking mediapipe_api/mediapipe_c.dll failed: (Exit 1120): link.exe failed: error executing command (from target //mediapipe_api:mediapipe_c.dll) 
  cd /d C:/_bzl/kvkvswqe/execroot/mediapipe_api
  SET LIB=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\ATLMFC\lib\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\lib\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22000.0\\um\x64
    SET PATH=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\VCPackages;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\bin\Roslyn;C:\Program Files\Microsoft Visual Studio\2022\Community\Team Tools\Performance Tools\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools;C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\\x64;C:\Program Files (x86)\Windows Kits\10\bin\\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\\MSBuild\Current\Bin\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\;;C:\WINDOWS\system32;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\Linux\bin\ConnectionManagerExe
    SET PROCESSOR_ARCHITECTURE=AMD64
    SET PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 154 Stepping 3, GenuineIntel
    SET PROCESSOR_LEVEL=6
    SET PROCESSOR_REVISION=9a03
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C://Python311//python.exe
    SET ProgramData=C:\ProgramData
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\charl\AppData\Local\Temp
    SET TMP=C:\Users\charl\AppData\Local\Temp
  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\link.exe @bazel-out/x64_windows-opt/bin/mediapipe_api/mediapipe_c.dll-2.params
# Configuration: 38e1efb2e93c87aac524b3889c1725dd2ef8635de09243c934691c1ef154cf21
# Execution platform: @local_execution_config_platform//:platform
   Creating library bazel-out/x64_windows-opt/bin/mediapipe_api/mediapipe_c.dll.if.lib and object bazel-out/x64_windows-opt/bin/mediapipe_api/mediapipe_c.dll.if.exp 
LINK : warning LNK4217: symbol 'TfLiteXNNPackDelegateOptionsDefault' defined in 'xnnpack_delegate.lib(xnnpack_delegate.obj)' is imported by 'inference_calculator_cpu.lo.lib(inference_calculator_cpu.obj)' in function '"private: class absl::lts_20230125::StatusOr<class std::unique_ptr<struct TfLiteDelegate,class std::function<void __cdecl(struct TfLiteDelegate *)> > > __cdecl mediapipe::api2::InferenceCalculatorCpuImpl::MaybeCreateDelegate(class mediapipe::CalculatorContext *)" (?MaybeCreateDelegate@InferenceCalculatorCpuImpl@api2@mediapipe@@AEAA?AV?$StatusOr@V?$unique_ptr@UTfLiteDelegate@@V?$function@$$A6AXPEAUTfLiteDelegate@@@Z@std@@@std@@@lts_20230125@absl@@PEAVCalculatorContext@3@@Z)'
LINK : warning LNK4286: symbol 'TfLiteXNNPackDelegateOptionsDefault' defined in 'xnnpack_delegate.lib(xnnpack_delegate.obj)' is imported by 'tflite_inference_calculator.lo.lib(tflite_inference_calculator.obj)'
LINK : warning LNK4217: symbol 'TfLiteXNNPackDelegateCreate' defined in 'xnnpack_delegate.lib(xnnpack_delegate.obj)' is imported by 'inference_calculator_cpu.lo.lib(inference_calculator_cpu.obj)' in function '"private: class absl::lts_20230125::StatusOr<class std::unique_ptr<struct TfLiteDelegate,class std::function<void __cdecl(struct TfLiteDelegate *)> > > __cdecl mediapipe::api2::InferenceCalculatorCpuImpl::MaybeCreateDelegate(class mediapipe::CalculatorContext *)" (?MaybeCreateDelegate@InferenceCalculatorCpuImpl@api2@mediapipe@@AEAA?AV?$StatusOr@V?$unique_ptr@UTfLiteDelegate@@V?$function@$$A6AXPEAUTfLiteDelegate@@@Z@std@@@std@@@lts_20230125@absl@@PEAVCalculatorContext@3@@Z)'
LINK : warning LNK4286: symbol 'TfLiteXNNPackDelegateCreate' defined in 'xnnpack_delegate.lib(xnnpack_delegate.obj)' is imported by 'tflite_inference_calculator.lo.lib(tflite_inference_calculator.obj)'
LINK : warning LNK4217: symbol 'TfLiteXNNPackDelegateDelete' defined in 'xnnpack_delegate.lib(xnnpack_delegate.obj)' is imported by 'inference_calculator_cpu.lo.lib(inference_calculator_cpu.obj)' in function '"private: class absl::lts_20230125::StatusOr<class std::unique_ptr<struct TfLiteDelegate,class std::function<void __cdecl(struct TfLiteDelegate *)> > > __cdecl mediapipe::api2::InferenceCalculatorCpuImpl::MaybeCreateDelegate(class mediapipe::CalculatorContext *)" (?MaybeCreateDelegate@InferenceCalculatorCpuImpl@api2@mediapipe@@AEAA?AV?$StatusOr@V?$unique_ptr@UTfLiteDelegate@@V?$function@$$A6AXPEAUTfLiteDelegate@@@Z@std@@@std@@@lts_20230125@absl@@PEAVCalculatorContext@3@@Z)'
LINK : warning LNK4286: symbol 'TfLiteXNNPackDelegateDelete' defined in 'xnnpack_delegate.lib(xnnpack_delegate.obj)' is imported by 'tflite_inference_calculator.lo.lib(tflite_inference_calculator.obj)'
face_detection_options_registry.lo.lib(face_detection_options_lib.obj) : error LNK2019: unresolved external symbol "private: static class RegistrationToken::RegistrationToken const mediapipe::tool::OptionsRegistry::registration_token<class mediapipe::FaceDetectionOptions>" (??$registration_token@VFaceDetectionOptions@mediapipe@@@OptionsRegistry@tool@mediapipe@@0VRegistrationToken@3@B) referenced in function "??__E?$registration_token@VFaceDetectionOptions@mediapipe@@@OptionsRegistry@tool@mediapipe@@YAXXZ" (??__E?$registration_token@VFaceDetectionOptions@mediapipe@@@OptionsRegistry@tool@mediapipe@@YAXXZ)
inference_calculator_options_registry.lo.lib(inference_calculator_options_lib.obj) : error LNK2019: unresolved external symbol "private: static class RegistrationToken::RegistrationToken const mediapipe::tool::OptionsRegistry::registration_token<class mediapipe::InferenceCalculatorOptions>" (??$registration_token@VInferenceCalculatorOptions@mediapipe@@@OptionsRegistry@tool@mediapipe@@0VRegistrationToken@3@B) referenced in function "??__E?$registration_token@VInferenceCalculatorOptions@mediapipe@@@OptionsRegistry@tool@mediapipe@@YAXXZ" (??__E?$registration_token@VInferenceCalculatorOptions@mediapipe@@@OptionsRegistry@tool@mediapipe@@YAXXZ)
bazel-out\x64_windows-opt\bin\mediapipe_api\mediapipe_c.dll : fatal error LNK1120: 2 unresolved externals
Target //mediapipe_api:mediapipe_desktop failed to build
INFO: Elapsed time: 610.002s, Critical Path: 310.43s
INFO: 3696 processes: 1259 internal, 2437 local.                                                                                                                     
FAILED: Build did NOT complete successfully                                                                                                                          
Traceback (most recent call last):
  File "C:\Users\charl\dev\getfilta\nplus1\packages\mpup\build.py", line 470, in <module>
    Argument().command().run()
  File "C:\Users\charl\dev\getfilta\nplus1\packages\mpup\build.py", line 143, in run
    self._run_command(self._build_desktop_commands())
  File "C:\Users\charl\dev\getfilta\nplus1\packages\mpup\build.py", line 56, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\subprocess.py", line 569, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Python311//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures --define MEDIAPIPE_DISABLE_GPU=1 --@opencv//:switch=cmake //mediapipe_api:mediapipe_desktop' returned non-zero exit status 1.
```

### Additional Context

the relevant part of the log output:

```
inference_calculator_options_registry.lo.lib(inference_calculator_options_lib.obj) : error LNK2019: unresolved external symbol "private: static class RegistrationToken::RegistrationToken const mediapipe::tool::OptionsRegistry::registration_token<class mediapipe::InferenceCalculatorOptions>" (??$registration_token@VInferenceCalculatorOptions@mediapipe@@@OptionsRegistry@tool@mediapipe@@0VRegistrationToken@3@B) referenced in function "??__E?$registration_token@VInferenceCalculatorOptions@mediapipe@@@OptionsRegistry@tool@mediapipe@@YAXXZ" (??__E?$registration_token@VInferenceCalculatorOptions@mediapipe@@@OptionsRegistry@tool@mediapipe@@YAXXZ)
```

**Comment by homuler** [comment]
Identifying the cause of this type of issue can be challenging, since it is due to the local environments.
If no errors occur with Docker or GitHub Actions, please consider using those platforms.

**Comment by emphaticaditya** [comment]
Facing a similar issue while building it on Windows. Any ideahow to resolve this? @homuler @cdiddy77

**Comment by emphaticaditya** [comment]
![error](https://github.com/homuler/MediaPipeUnityPlugin/assets/20595344/fa36e2b3-6110-4595-a194-b31b05cbf2ad)
Error ^^
